f = 2
vspeed = (48 / f)
image_angle = irandom(359)
x = (o_boxingqueen.x - 5)
state = 0
depth = (o_boxingqueen.depth - 2)
image_xscale = 1.75
image_yscale = 1.75
roll = 1
throw_xspeed = -12
throw_yspeed = -14
grav = 1
max_yspeed = 40
roll_angle = 0
prevx = x
xdiff = 0
moving_dir = 0
max_syspeed = 0
