event_inherited()
hp = 3
offset = 200
subindex = 0
animtimer = 0
drawcolor = c_white
flash = false
image_yscale = 10
image_xscale = 2
difficulty = 1
slidedir = (randomsign() * random_range(2, 6))
destroying = 0
shoottimer = 29
vspeed = choose(4, -4)
topy = (obj_growtangle.y - 60)
bottomy = (obj_growtangle.y + 60)
vbounce = 1
updown = 1
crushedObj = 0
maxspeed = 8
destroyonhit = false
offsetCap = 0
crushtimer = 0
init = false
siner = 0
pushback = 0
startdepth = depth
flashsiner = 0
