thrash = obj_rouxls_enemy.thrash
btimer = 0
shotcount = 0
shotbuffer = 1
siner = 0
damage = 4
flip = randomsign()
attackangle = 0
damage = -1
target = -1
grazepoints = 4
difficulty = 0
shotfired = 0
initialspeed = random_range(0, 1)
