image_index = 1
image_speed = 0
siner = random(20)
timer = 0
image_angle = 270
image_xscale = 2
image_yscale = 2.3
hspeed = -6
lastType = -1
damage = 10
con = 0
movetimer = 0
x = ((camerax() + camerawidth()) + 100)
