xx = __view_get((0 << 0), 0)
yy = __view_get((1 << 0), 0)
condition = 0
attackno = 0
attack = 0
image_xscale = 2
image_yscale = 2
x = (xx + 470)
y = (yy + 70)
active = true
faketimer = 0
faketimermax = 180
timeruse = false
image_speed = 0.334
