type = 1
btimer = 99
timermax = 12
damage = -1
grazepoints = -1
timepoints = -1
inv = -1
grazed = -1
grazetimer = -1
element = 6
target = -1
side = 1
difficulty = 1
made = 0
special = false
init = false
sameattack = false
sameattacker = false
miny = 999
maxy = 999
maxx = 999
miny = 999
creator = obj_sneo_friedpipis
sneo = obj_spamton_neo_enemy
hideshooty = 1
lastType = 0
sneoarm_x = (sneo.x + sneo.partxoff[1])
sneoarm_y = (sneo.y + sneo.partyoff[1])
