timer = 0
con = 0
x1 = (camerax() + 322)
y1 = (cameray() + 68)
x2 = (camerax() + 322)
y2 = (cameray() + 68)
depth = (obj_ch2_scene10.kr_actor.depth + 2)
kr_x_save = obj_ch2_scene10.kr_actor.x
kr_y_save = obj_ch2_scene10.kr_actor.y
su_x_save = obj_ch2_scene10.su_actor.x
su_y_save = obj_ch2_scene10.su_actor.y
ra_x_save = obj_ch2_scene10.ra_actor.x
ra_y_save = obj_ch2_scene10.ra_actor.y
qu_x_save = obj_ch2_scene10.qu_actor.x
qu_y_save = obj_ch2_scene10.qu_actor.y
punch_r_timer = 0
punch_l_timer = 0
dodge_r_timer = 0
dodge_l_timer = 0
dodge_d_timer = 0
