d = instance_create(x, (y - 17), obj_regularbullet)
d.damage = damage
d.target = target
d.sprite_index = spr_hitbox_10px
d.direction = 180
d.speed = 45
d.image_xscale = 10
d.image_yscale = 3.5
d.visible = false
d.damage = damage
d.target = target
