siner = 0
rot = 0
xscale = 0
yscale = 0
xcen = 320
ycen = 240
radius = 360
dkblue = merge_color(c_navy, c_dkgray, 0.1)
dkblue2 = merge_color(c_navy, c_dkgray, 0.5)
dkblue3 = merge_color(c_navy, c_dkgray, 0.5)
dkblue3 = merge_color(dkblue3, c_black, 0.2)
bgx = 0
rotcounter = 0
rotfps = 1
rotspeed = 0
bgx = 0
check = 0
on = 0
bgalpha = 0
