image_speed = 0
image_index = 0
x = 226
y = 85
con = 0
heartwagon = 0
sprite_index = spr_dkris_bedstruggle_ch1
wagon = scr_marker_ch1(235, 165, spr_wheelbarrow_small_ch1)
cageshake = 0
cageamt = 0
shaketimer = 0
heartx = 0
hearty = 0
