image_xscale = 2
image_yscale = 2
counter = 0
image_angle = 0
seizure = 0
hspeed = (-7.6 - random(1.5))
vspeed = (-2 + random(4))
gravity = 0.13
gravity_direction = 0
active = true
timepoints = 4
grazepoints = 4
damage = 30
grazed = false
