scr_bullet_init()
timer = 0
rotateposition = 0
lengthtimer = 0
lengthstate = 0
destroyonhit = false
image_speed = 0
impact = 0
direction = point_direction(obj_growtangle.x, obj_growtangle.y, x, y)
bufferstate = 0
loading = 9
parentwindow = -4
image_index = 2
flip = (x < obj_growtangle.x ? -1 : 1)
hitstun = 0
broken = 0
chainlength = 0
maxchainlength = 180
image_xscale = 1
image_yscale = 1
image_blend = 0x89D931
