if (!i_ex(target))
    instance_destroy()
if instance_exists(obj_sneo_biglaser_elevator)
    depth = (obj_sneo_biglaser_elevator.depth + 1)
if instance_exists(obj_heart)
    depth = (obj_heart.depth + 1)
