image_xscale = 0
image_yscale = 0
image_alpha = 0.3
maxtimer = 15
timeincrease = 1
timer = (maxtimer - timeincrease)
growcon = 1
image_speed = 0
image_blend = merge_color(c_green, c_lime, 0.5)
target_angle = 0
fullgrow = 0
keep = 0
megakeep = 0
maxxscale = obj_growtangle.maxxscale
maxyscale = obj_growtangle.maxyscale
sprite_index = obj_growtangle.spr_custom_box
obj_growtangle.depth -= 2
depth = (obj_growtangle.depth + 1)
