fakegrav = 0
fakey = 0
fakeyspeed = 0
image_xscale = 2
image_yscale = 2
timer = 0
con = 0
hspeed = random_range(-16, -6)
vspeed = random_range(-3, 3)
fakeyspeed = (-2 - random(8))
fakegrav = 1
sineradd = 1
siner = random(8)
amplitude = 0
maxamplitude = (9 + random(5))
xx = camerax()
yy = cameray()
creator = obj_maus_split
captured = 0
