image_xscale = 2
image_yscale = 2
con = 0
mode = choose(1, 2)
content = 2
contentsprite = spr_ch2_gimmick_saucer_dog
myinteract = 0
image_speed = 0
multiplier = 2
collider = obj_sneo_friedpipis
collider = instance_create((x + 8), (y + 22), obj_solidblock)
collider.image_xscale = 4.2
collider.image_yscale = 3
xoffset = 0
yoffset = 0
itemid = 1
itemtype = "item"
itemflag = 118
activated = false
checked = false
activated_bomb = 0
montyboss = 0
