with (o_coaster_berdly)
    instance_destroy()
with (o_coaster_hero)
    instance_destroy()
with (o_coaster_controller)
    instance_destroy()
with (obj_herokris)
    instance_destroy()
instance_create(x, y, o_berdly_coaster_end_fix)
