unused_0 = gml_Script_scr_84_get_lang_string_ch1("UNUSED_slash_UNUSED_gml_1_0")
unused_1 = gml_Script_scr_84_get_lang_string_ch1("UNUSED_slash_UNUSED_gml_2_0")
unused_2 = gml_Script_scr_84_get_lang_string_ch1("UNUSED_slash_UNUSED_gml_3_0")
unused_3 = gml_Script_scr_84_get_lang_string_ch1("UNUSED_slash_UNUSED_gml_4_0")
unused_4 = gml_Script_scr_84_get_lang_string_ch1("UNUSED_slash_UNUSED_gml_5_0")
unused_5 = gml_Script_scr_84_get_lang_string_ch1("UNUSED_slash_UNUSED_gml_6_0")
unused_6 = gml_Script_scr_84_get_lang_string_ch1("UNUSED_slash_UNUSED_gml_7_0")
unused_7 = gml_Script_scr_84_get_lang_string_ch1("UNUSED_slash_UNUSED_gml_8_0")
unused_8 = gml_Script_scr_84_get_lang_string_ch1("UNUSED_slash_UNUSED_gml_9_0")
unused_9 = gml_Script_scr_84_get_lang_string_ch1("UNUSED_slash_UNUSED_gml_10_0")
return;
