if (global.mnfight != 2)
    instance_destroy()
if (x < (gml_Script___view_get(0, 0) - sprite_width))
    instance_destroy()
if (x > ((gml_Script___view_get(0, 0) + 640) + sprite_width))
    instance_destroy()
if (y < (gml_Script___view_get(1, 0) - sprite_height))
    instance_destroy()
if (y > ((gml_Script___view_get(1, 0) + 480) + sprite_height))
    instance_destroy()
return;
