if gml_Script_scr_debug()
{
    camx = gml_Script___view_get(0, 0)
    camy = gml_Script___view_get(1, 0)
    camx = (argument0 + gml_Script_camerax())
    camy = (argument1 + gml_Script_cameray())
    draw_set_font(fnt_small)
    draw_set_color(c_black)
    draw_text(camx, camy, argument2)
    draw_text((camx + 1), camy, argument2)
    draw_text((camx + 1), (camy + 1), argument2)
    draw_text((camx + 1), (camy - 1), argument2)
    draw_text((camx - 1), camy, argument2)
    draw_text((camx - 1), (camy + 1), argument2)
    draw_text((camx - 1), (camy - 1), argument2)
    draw_text(camx, (camy - 1), argument2)
    draw_text((camx + 1), (camy - 1), argument2)
    draw_text((camx - 1), (camy - 1), argument2)
    draw_text(camx, (camy + 1), argument2)
    draw_text((camx + 1), (camy + 1), argument2)
    draw_text((camx - 1), (camy + 1), argument2)
    draw_set_color(c_gray)
    draw_text(camx, camy, argument2)
}
return;
