if (obj_spamton_neo_enemy.partmode != 3)
    instance_destroy()
if instance_exists(obj_sneo_biglaser)
    depth = (obj_sneo_biglaser.depth + 1)
if instance_exists(obj_heart)
    depth = (obj_heart.depth + 1)
