// WARNING: Popz'd an empty stack.
obj_battlecontroller.hidemercy = 1
depth = (obj_battlecontroller.depth - 3)
talkmax = 180
image_speed = 0.16666666666666666
idlesprite = spr_hatguy_idle
hurtsprite = spr_hatguy_idle
sparedsprite = spr_hatguy_idle
recruitable = 0
dancing = 0
danceCounter = 0
dancedwithsusie = 0
heal = 0
learnedAct = 0
helpusattack = 0
ishealing = 0
postattackscene = 0
groove = 0
siner2 = 10
musicalnotetimer = 0
hurtstate2 = 0
