image_xscale = 2
image_yscale = 2
image_speed = 0
image_blend = c_white
depth = -50
image_speed = 0
winetimer = 0
con = 0
siner = 0
introtimer = 0
timer = 0
angle_speed = 0
obj_queen_enemy.sprite_index = spr_queen_throw_wineglass
_remx = (obj_queen_enemy.x + 29)
_remy = (obj_queen_enemy.y + 50)
_idealx = x
_idealy = y
fill_yscale = 1
fill_yscale_gradual = 1
