sprite_delete(mysprite[0])
sprite_delete(mysprite[1])
sprite_delete(mysprite[2])
mysprite[0] = sprite_duplicate(sprite[0])
mysprite[1] = sprite_duplicate(sprite[1])
mysprite[2] = sprite_duplicate(sprite[2])
