var _temp_local_var_1;
cityscape_bg_0 = gml_Script_instance_create(0, 0, obj_looping_tiled_area)
cityscape_bg_0.sprite_index = spr_cyber_coaster_bg_tile
cityscape_bg_0.width = ((3140 * 2) * 3)
cityscape_bg_0.height = (3140 - 1)
cityscape_bg_0.room_wide = 1
cityscape_bg_0.depth = 1000500
cityscape_bg_0.x_scale = 1
cityscape_bg_0.y_scale = 1
cityscape_bg_1 = gml_Script_instance_create(0, 0, obj_looping_tiled_area)
cityscape_bg_1.sprite_index = spr_cyber_coaster_bg_cityscape_bg
cityscape_bg_1.width = ((3141 * 2) * 3)
cityscape_bg_1.height = (3141 - 1)
cityscape_bg_1.room_wide = 1
cityscape_bg_1.depth = 1000400
cityscape_bg_1.x_scale = 1
cityscape_bg_1.y_scale = 1
cityscape_bg_2 = gml_Script_instance_create(0, 0, obj_looping_tiled_area)
cityscape_bg_2.sprite_index = spr_cyber_coaster_bg_cityscape_fg
cityscape_bg_2.width = ((3142 * 2) * 3)
cityscape_bg_2.height = (3142 - 1)
cityscape_bg_2.room_wide = 1
cityscape_bg_2.depth = 1000300
cityscape_bg_2.x_scale = 1
cityscape_bg_2.y_scale = 1
coaster_bg_1 = gml_Script_instance_create(815, 64, obj_looping_tiled_area)
coaster_bg_1.sprite_index = bg_dw_city_coaster_track_fullwidth
coaster_bg_1.width = ((3176 * 2) * 3)
coaster_bg_1.height = (3176 - 1)
coaster_bg_1.room_wide = 1
coaster_bg_1.depth = 1000200
coaster_bg_1.x_scale = 1
coaster_bg_1.y_scale = 1
for (var i = 0; i < 3; i++)
{
    coaster_track[i] = gml_Script_instance_create(815, (130 + (i * 60)), obj_looping_tiled_area)
    coaster_track[i].sprite_index = spr_cyber_coaster_track
    coaster_track[i].width = ((3137 * 2) * 7)
    coaster_track[i].height = (3137 - 1)
    coaster_track[i].room_wide = 1
    coaster_track[i].depth = 1000100
    coaster_track[i].x_scale = 1
    coaster_track[i].y_scale = 1
}
parallax = 1
looping = 0
fountain = gml_Script_scr_marker_animated(815, 0, 3139)
var _temp_local_var_1 = fountain
depth = 1000450
image_speed = 0.125
