image_xscale = 0.2
image_yscale = 1
image_speed = 0.5
image_index = irandom(15)
image_blend = c_yellow
sprite_index = spr_sneo_c_weakpoint_growth2
good = 1
offing = 0
con = 1
collided = 0
siner = random(500)
n = (random(15) / 200)
vineid = -1
stopmoving = 0
growstate = 0
