global.lcharname = "scr_gamestart_slash_scr_gamestart_gml_345_0"
global.charname[0] = " "
global.charname[1] = "obj_initializer_slash_Create_0_gml_48_0"
global.charname[2] = "obj_initializer_slash_Create_0_gml_49_0"
global.charname[3] = "obj_initializer_slash_Create_0_gml_50_0"
