// WARNING: Popz'd an empty stack.
image_alpha = 0
image_speed = 0
image_xscale = 2
image_yscale = 2
timer = 0
con = 0
mysolid = 0
init = 0
h = 0
w = 0
returntoxy = 0
movetimer = 0
kiratimer = 0
skipsound = 0
skipsolid = 0
depth = 0
specialinit = 0
specialcolor = merge_color(c_navy, c_white, 0.8)
fresh = 0
inbattle = 0
