event_inherited()
usprite = spr_queen_chair_swish_wine
rsprite = spr_queen_chair_swish_wine
dsprite = spr_queen_chair_swish_wine
lsprite = spr_queen_chair_swish_wine
name = "queen"
fakey = -80
yoff = 0
float = 0
floaty = 0
shadow = 0
floatsiner = 0
image_speed = 0.1
fakeshadow = gml_Script_scr_dark_marker(x, y, sprite_index)
fakeshadow.depth = 500000
fakeshadow.image_xscale = 2
fakeshadow.visible = false
fakeshadow.image_yscale = 0.25
fakeshadow.image_speed = 0
specialsprite[0] = 759
specialsprite[1] = 761
