w = sprite_width
h = sprite_height
chyoffset = 50
chsprite = 2992
chnum = global.chapter
NOISE = 256
siner = 0
factor = 1
factor2 = 0
factory = (h / 2)
mid = (h / 2)
x = ((gml_Script___view_get(2, 0) / 2) - (w / 2))
y = (((gml_Script___view_get(3, 0) / 2) - (h / 2)) - 10)
inity = y
PHASE = 0
PHASETIMER = 0
PHASEPLUS = 0
AA = 1
AB = 1
ingame = 1
if (global.plot == 0)
    ingame = 0
skipped = 0
skiptimer = 0
room_speed = 15
draw_screen = 1
