var colo = draw_get_color()
draw_set_colour(0x00C000)
draw_rectangle((left - 4), (top - 4), (right + 4), (bottom + 4), false)
draw_set_colour(c_black)
draw_rectangle(left, top, right, bottom, false)
draw_set_colour(colo)
