image_yscale = 0
image_xscale = 0
xrange = 0
vspeed = 0.1
gravity = 0.02
init = false
depth = (o_boxingcontroller.depth + 1)
animtimer = 0
flip = 1
create_hitbox = 0
rep = 2
variant = 0
playsounds = 0
