myinteract = 0
talked = 0
checked = false
global.flag[32] = 0
image_xscale = 2
image_yscale = 2
con = 0
image_speed = 0
teleportmode = 0
door_destination = room
door_location = room
on = 1
weirdlight = gml_Script_scr_dark_marker_ch1((x + 6), (y + 96), 3719)
var _temp_local_var_1 = weirdlight
depth = 895000
image_speed = 0.125
