siner = 0
targetx = 0
wing_index = 0
wingtimer = 0
shot = 0
xmake = 2
attacktimer = 0
attackcon = -1
shakefactor = 4
side = 1
loc_check = 0
mazemode = 0
beatcon = 0
introcon = 0
introtimer = 0
shadowy = (y + 160)
shadow = gml_Script_scr_dark_marker(x, shadowy, sprite_index)
var _temp_local_var_1 = shadow
sprite_index = spr_starwalker_wings
image_yscale = 0.25
image_blend = c_black
depth = 600000
