event_inherited()
image_index = 2
image_speed = 0
y = -30
depth = (obj_heart.depth - 1)
timer = 0
con = 0
flash = false
siner = 0
destroyable = 1
destroyonhit = 0
swingdir = 1
myspeed = -4
length = 170
place = 50
swing = 0
target_x = (gml_Script_camerax() + 240)
target_y = -10
sneoarmtimer = 0
