left = (obj_growtangle.x - (obj_growtangle.sprite_width / 2))
right = (obj_growtangle.x + (obj_growtangle.sprite_width / 2))
top = (obj_growtangle.y - (obj_growtangle.sprite_height / 2))
bottom = (obj_growtangle.y + (obj_growtangle.sprite_height / 2))
maxleft = left
maxright = right
maxtop = top
maxbottom = bottom
init = false
sizeup = 0
playercrush = 0
target = 0
damage = 30
destroytimer = 0
