if (obj_mainchara.x > (x - 60) && con == -1)
{
    con = 1
    global.interact = 1
    global.facing = 1
    var noelle_x = obj_caterpillarchara.x
    var noelle_y = obj_caterpillarchara.y
    gml_Script_scr_losechar()
    instance_destroy(obj_caterpillarchara)
    gml_Script_scr_getchar(2)
    gml_Script_scr_getchar(3)
    gml_Script_scr_makecaterpillar((gml_Script_camerax() - 260), 205, 2, 0)
    gml_Script_scr_makecaterpillar((gml_Script_camerax() - 200), 200, 3, 1)
    cutscene_master = gml_Script_scr_cutscene_make()
    gml_Script_scr_maincharacters_actors()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(818)
    gml_Script_c_autowalk(0)
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(141)
    gml_Script_c_autowalk(0)
    qu = 5
    qu_actor = gml_Script_instance_create((gml_Script_camerax() + 700), 167, obj_actor)
    gml_Script_scr_actor_setup(qu, qu_actor, "queen")
    qu_actor.sprite_index = spr_queen_walk_left
    no = 6
    no_actor = gml_Script_instance_create(noelle_x, noelle_y, obj_actor)
    gml_Script_scr_actor_setup(no, no_actor, "noelle")
    no_actor.sprite_index = spr_noelle_walk_right_dw
    be = 7
    be_actor = gml_Script_instance_create((gml_Script_camerax() + 760), 229, obj_actor)
    gml_Script_scr_actor_setup(be, be_actor, "berdly")
    be_actor.sprite_index = spr_berdly_walk_left_lw
    gi = 8
    gi_actor = gml_Script_instance_create((gml_Script_camerax() + 760), 200, obj_actor)
    gml_Script_scr_actor_setup(gi, gi_actor, "gift")
    gi_actor.sprite_index = spr_cutscene_15_gift
    gml_Script_c_sel(gi)
    gml_Script_c_autodepth(0)
    gift = gml_Script_scr_dark_marker((gml_Script_camerax() + 1000), 120, 158)
    healimpact = gml_Script_scr_dark_marker((gml_Script_camerax() + 1000), 120, 147)
    boxhead = gml_Script_scr_dark_marker((gml_Script_camerax() + 1000), 120, 99)
    ralsei_ball = gml_Script_scr_dark_marker((gml_Script_camerax() + 1000), 120, 150)
    if (havewalker == 1)
    {
        starwalker = gml_Script_scr_dark_marker((gml_Script_camerax() - 500), 239, 1208)
        cutscene_master.save_object[4] = starwalker
    }
    cutscene_master.save_object[0] = gift
    cutscene_master.save_object[1] = healimpact
    cutscene_master.save_object[2] = boxhead
    cutscene_master.save_object[3] = ralsei_ball
}
if (con == 1)
{
    con = 2
    gml_Script_c_mus2("volume", 0, 30)
    gml_Script_c_sel(kr)
    gml_Script_c_delayfacing(16, "r")
    gml_Script_c_soundplay(292)
    gml_Script_c_sel(no)
    gml_Script_c_sprite(716)
    gml_Script_c_wait(30)
    gml_Script_c_wait(10)
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\EE* O-oh no^1, she's coming back this way!!/", "obj_ch2_city07_slash_Step_0_gml_91_0")
    gml_Script_c_msgnextloc("\\EE* I'll hide in that stall!/%", "obj_ch2_city07_slash_Step_0_gml_92_0")
    gml_Script_c_talk_wait()
    gml_Script_c_var_instance(tentback, "depth", (no_actor.depth + 100000))
    gml_Script_c_autowalk(1)
    gml_Script_c_walkdirect_wait(1276, 139, 11)
    gml_Script_c_autodepth(0)
    gml_Script_c_depth(97900)
    gml_Script_c_walkdirect_wait(1371, 139, 11)
    gml_Script_c_facing("d")
    gml_Script_c_wait(15)
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(111)
    gml_Script_c_imageindex(0)
    gml_Script_c_imagespeed(0.4)
    gml_Script_c_wait(20)
    gml_Script_c_sel(no)
    gml_Script_c_imagespeed(0)
    gml_Script_c_wait(15)
    gml_Script_c_mus("free_all")
    gml_Script_c_mus2("initloop", "queen.ogg", 0)
    gml_Script_c_pannable(1)
    gml_Script_c_pan(1070, 0, 30)
    gml_Script_c_sel(kr)
    gml_Script_c_walkdirect(1301, 234, 40)
    gml_Script_c_delayfacing(41, "r")
    gml_Script_c_sel(qu)
    gml_Script_c_autodepth(0)
    gml_Script_c_depth(10000)
    gml_Script_c_walkdirect_wait(1456, 183, 40)
    gml_Script_c_wait(30)
    gml_Script_c_speaker("queen")
    gml_Script_c_msgside("bottom")
    gml_Script_c_msgsetloc(0, "\\E9* Hey Check This Out/%", "obj_ch2_city07_slash_Step_0_gml_139_0")
    gml_Script_c_talk_wait()
    gml_Script_c_walkdirect_wait(1495, 225, 20)
    gml_Script_c_wait(1)
    gml_Script_c_autowalk(0)
    gml_Script_c_facing("l")
    gml_Script_c_wait(10)
    gml_Script_c_imagespeed(0)
    gml_Script_c_wait(10)
    gml_Script_c_setxy(1451, 220)
    gml_Script_c_sprite(140)
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0)
    gml_Script_c_imageindex(0)
    gml_Script_c_wait(5)
    gml_Script_c_imageindex(1)
    gml_Script_c_wait(20)
    gml_Script_c_imageindex(2)
    gml_Script_c_wait(2)
    gml_Script_c_imageindex(3)
    gml_Script_c_wait(1)
    gml_Script_c_imageindex(4)
    gml_Script_c_wait(1)
    gml_Script_c_var_lerp_instance(ralsei_ball, "x", 1530, 1348, 5)
    gml_Script_c_var_lerp_instance(ralsei_ball, "y", 264, 145, 5)
    gml_Script_c_wait(5)
    gml_Script_c_var_instance(ralsei_ball, "visible", 0)
    gml_Script_c_var_instance(id, "hit_bottles", 1)
    gml_Script_c_sel(no)
    gml_Script_c_sprite(98)
    gml_Script_c_halt()
    gml_Script_c_visible(1)
    gml_Script_c_wait(5)
    gml_Script_c_shakeobj()
    gml_Script_c_wait(55)
    gml_Script_c_sel(qu)
    gml_Script_c_setxy(1495, 225)
    gml_Script_c_sprite(769)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walkdirect_wait(1456, 183, 15)
    gml_Script_c_sprite(771)
    gml_Script_c_wait(15)
    gml_Script_c_speaker("queen")
    gml_Script_c_msgsetloc(0, "\\EQ* Sweet Right/%", "obj_ch2_city07_slash_Step_0_gml_200_0")
    gml_Script_c_talk_wait()
    gml_Script_c_autowalk(1)
    gml_Script_c_walkdirect_wait(1456, 125, 20)
    gml_Script_c_sprite(771)
    gml_Script_c_wait(15)
    gml_Script_c_speaker("queen")
    gml_Script_c_msgsetloc(0, "\\E9* Where's My Prize/%", "obj_ch2_city07_slash_Step_0_gml_209_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(no)
    gml_Script_c_sprite(100)
    gml_Script_c_halt()
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\EE* Oh! Um.../%", "obj_ch2_city07_slash_Step_0_gml_217_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(no)
    gml_Script_c_sprite(100)
    gml_Script_c_halt()
    gml_Script_c_sel(gi)
    gml_Script_c_setxy(1400, 155)
    gml_Script_c_soundplay(172)
    gml_Script_c_wait(15)
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\EE* H-here!/%", "obj_ch2_city07_slash_Step_0_gml_231_0")
    gml_Script_c_talk_wait()
    gml_Script_c_var_lerp_instance(gi_actor, "x", 1400, 1430, 6)
    gml_Script_c_wait(8)
    gml_Script_c_sel(gi)
    gml_Script_c_stickto(qu_actor, -10)
    gml_Script_c_wait(15)
    gml_Script_c_speaker("queen")
    gml_Script_c_msgsetloc(0, "\\EQ* Ha Ha Nice/%", "obj_ch2_city07_slash_Step_0_gml_242_0")
    gml_Script_c_talk_wait()
    gml_Script_c_wait(10)
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_sel(qu)
    gml_Script_c_facing("r")
    gml_Script_c_sel(gi)
    gml_Script_c_setxy(1500, 160)
    gml_Script_c_stickto(qu_actor, -10)
    gml_Script_c_sel(qu)
    gml_Script_c_walkdirect_wait(1590, 183, 20)
    gml_Script_c_wait(25)
    gml_Script_c_speaker("queen")
    gml_Script_c_msgsetloc(0, "\\ED* Wait I Actually Don't Want This/%", "obj_ch2_city07_slash_Step_0_gml_262_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(no)
    gml_Script_c_sprite(98)
    gml_Script_c_halt()
    gml_Script_c_sel(qu)
    gml_Script_c_facing("l")
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_setxy(1555, 220)
    gml_Script_c_stickto(qu_actor, -10)
    gml_Script_c_sel(qu)
    gml_Script_c_walkdirect_wait(1355, 183, 25)
    gml_Script_c_wait(10)
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_wait(5)
    gml_Script_c_autowalk(0)
    gml_Script_c_walkdirect_wait(1296, 195, 5)
    gml_Script_c_stickto(kr_actor, -10)
    gml_Script_c_wait(20)
    gml_Script_c_sel(qu)
    gml_Script_c_walk("r", 12, 90)
    gml_Script_c_mus2("volume", 0, 30)
    gml_Script_c_sel(su)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walk("r", 3, 60)
    gml_Script_c_sel(ra)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walk("r", 3, 60)
    gml_Script_c_pannable(1)
    gml_Script_c_panspeed(-4.5, 0, 60)
    gml_Script_c_wait(60)
    gml_Script_c_mus("free_all")
    gml_Script_c_sel(su)
    gml_Script_c_halt()
    gml_Script_c_sel(ra)
    gml_Script_c_halt()
    gml_Script_c_sel(kr)
    gml_Script_c_facing("l")
    gml_Script_c_wait(15)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E2* Hahaha^1, how was THAT!?/", "obj_ch2_city07_slash_Step_0_gml_326_0")
    gml_Script_c_facenext("ralsei", 2)
    gml_Script_c_msgnextloc("\\E2* Haha^1, Susie^1! You're not supposed to ATTACK people with it!/", "obj_ch2_city07_slash_Step_0_gml_328_0")
    gml_Script_c_facenext("susie", 2)
    gml_Script_c_msgnextloc("\\E2* Oh yeah!? Watch me!!!/%", "obj_ch2_city07_slash_Step_0_gml_330_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("r")
    gml_Script_c_emote("!", 30)
    gml_Script_c_sel(ra)
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("r")
    gml_Script_c_emote("!", 30)
    gml_Script_c_wait(30)
    gml_Script_c_walkdirect(1230, 200, 30)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\EP* Kris!!!!^1! There you are!!!/%", "obj_ch2_city07_slash_Step_0_gml_350_0")
    gml_Script_c_talk_wait()
    gml_Script_c_facing("r")
    gml_Script_c_pannable(1)
    gml_Script_c_pan(928, 0, 30)
    gml_Script_c_msgzurasu(1)
    gml_Script_c_sel(su)
    gml_Script_c_walkdirect(1159, 218, 30)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E7* Kris!^1! Check out my new attack!!/%", "obj_ch2_city07_slash_Step_0_gml_363_0")
    gml_Script_c_talk()
    gml_Script_c_wait(30)
    gml_Script_c_waittalk()
    gml_Script_c_msgzurasu(0)
    gml_Script_c_sel(ra)
    gml_Script_c_facing("d")
    gml_Script_c_sel(su)
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(145)
    gml_Script_c_arg_objectxy(su_actor, -39, -21)
    gml_Script_c_setxy(x, y)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_delaycmd(20, "sprite", 146)
    gml_Script_c_wait(30)
    gml_Script_c_var_instance(id, "susie_heal", 1)
    gml_Script_c_wait(40)
    gml_Script_c_soundplay(106)
    gml_Script_c_var_instance(id, "heal_effect", 1)
    gml_Script_c_sel(su)
    gml_Script_c_arg_objectxy(su_actor, 39, 21)
    gml_Script_c_setxy(x, y)
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("r")
    gml_Script_c_wait(60)
    gml_Script_c_speaker("no_name")
    gml_Script_c_msgsetloc(0, "* (You felt slightly healed.)/%", "obj_ch2_city07_slash_Step_0_gml_399_0")
    gml_Script_c_talk_wait()
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(818)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_sel(su)
    gml_Script_c_halt()
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E2* Heh^1, how's that!? Meet the new healing master^1, Kris!/%", "obj_ch2_city07_slash_Step_0_gml_412_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(812)
    gml_Script_c_setxy(1230, 206)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\EG * Oh. Yes. She is a real..^1. \"master\" at it^1, Kris./%", "obj_ch2_city07_slash_Step_0_gml_419_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_facing("d")
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EK* God^1, teaching you sarcasm was a mistake./", "obj_ch2_city07_slash_Step_0_gml_427_0")
    gml_Script_c_facenext("ralsei", "H")
    gml_Script_c_msgnextloc("\\EH* Hahahahaha!/%", "obj_ch2_city07_slash_Step_0_gml_429_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_facing("r")
    gml_Script_c_setxy(1229, 200)
    gml_Script_c_sel(su)
    gml_Script_c_facing("r")
    gml_Script_c_msc(1083)
    gml_Script_c_talk_wait()
}
if (con == 10)
{
    global.flag[307] = 1
    con = 2
    alarm[0] = 30
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_autowalk(0)
    gml_Script_c_walkdirect_wait(1225, 178, 15)
    gml_Script_c_stickto(ra_actor, -10)
    gml_Script_c_sel(ra)
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(786)
    gml_Script_c_wait(15)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\ED * H..^1. huh!? You're giving it to..^1. me...?/%", "obj_ch2_city07_slash_Step_0_gml_466_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sprite(797)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E0* Kris.../", "obj_ch2_city07_slash_Step_0_gml_472_0")
    gml_Script_c_msgnextloc("\\E1* I..^1. I've never gotten a gift like this before./", "obj_ch2_city07_slash_Step_0_gml_473_0")
    gml_Script_c_msgnextloc("\\E1* U..^1. ummm..^1. I'm sorry^1, I.../%", "obj_ch2_city07_slash_Step_0_gml_474_0")
    gml_Script_c_talk_wait()
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("u")
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E2* (I'm so happy^1, I don't really know what to say...)/", "obj_ch2_city07_slash_Step_0_gml_481_0")
    gml_Script_c_msgnextloc("\\E1* .../%", "obj_ch2_city07_slash_Step_0_gml_482_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_var_instance(gi_actor, "depth", (ra_actor + 100))
    gml_Script_c_var_lerp_instance(gi_actor, "y", 178, 164, 3)
    gml_Script_c_wait(3)
    gml_Script_c_var_lerp_instance(gi_actor, "y", 164, 214, 8)
    gml_Script_c_wait(8)
    gml_Script_c_soundplay(172)
    gml_Script_c_var_instance(gi_actor, "visible", 0)
    gml_Script_c_wait(15)
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(784)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E2* I..^1. I'll win something for you too^1, okay!?/%", "obj_ch2_city07_slash_Step_0_gml_500_0")
    gml_Script_c_talk_wait()
    gml_Script_c_pannable(1)
    gml_Script_c_pan(1074, 0, 30)
    gml_Script_c_sel(ra)
    gml_Script_c_walkdirect_wait(1439, 170, 30)
    gml_Script_c_facing("l")
    gml_Script_c_sel(kr)
    gml_Script_c_facing("r")
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\EH\\U* One baseball^1, please!!!/%", "obj_ch2_city07_slash_Step_0_gml_515_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_walkdirect_wait(1480, 230, 15)
    gml_Script_c_facing("l")
    gml_Script_c_wait(5)
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(149)
    gml_Script_c_arg_objectxy(ra_actor, -25, -5)
    gml_Script_c_setxy(x, y)
    gml_Script_c_halt()
    gml_Script_c_var_instance(boxhead, "x", no_actor.x)
    gml_Script_c_var_instance(boxhead, "y", no_actor.y)
    gml_Script_c_var_instance(boxhead, "depth", (no_actor.depth - 10))
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\EE* W-wait a second!!/%", "obj_ch2_city07_slash_Step_0_gml_535_0")
    gml_Script_c_talk_wait()
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_wait(10)
    gml_Script_c_var_instance(ralsei_ball, "x", 1467)
    gml_Script_c_var_instance(ralsei_ball, "y", 244)
    gml_Script_c_var_instance(ralsei_ball, "visible", 1)
    gml_Script_c_var_lerp_instance(ralsei_ball, "x", 1467, 1388, 5)
    gml_Script_c_var_lerp_instance(ralsei_ball, "y", 244, 165, 5)
    gml_Script_c_wait(5)
    gml_Script_c_var_instance(ralsei_ball, "visible", 0)
    gml_Script_c_wait(5)
    gml_Script_c_sel(ra)
    gml_Script_c_imagespeed(0)
    gml_Script_c_var_instance(id, "box_remove_effect", 1)
    gml_Script_c_sel(no)
    gml_Script_c_shakeobj()
    gml_Script_c_sprite(716)
    gml_Script_c_halt()
    gml_Script_c_var_instance(boxhead, "depth", 0)
    gml_Script_c_var_lerp_instance(boxhead, "y", no_actor.y, -100, 8)
    gml_Script_c_wait(30)
    gml_Script_c_sel(ra)
    gml_Script_c_flip("x")
    gml_Script_c_arg_objectxy(ra_actor, 20, 5)
    gml_Script_c_setxy(x, y)
    gml_Script_c_sprite(1506)
    gml_Script_c_shakeobj()
    gml_Script_c_sel(su)
    gml_Script_c_flip("x")
    gml_Script_c_sprite(995)
    gml_Script_c_shakeobj()
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E6* N..^1. Noelle!?/%", "obj_ch2_city07_slash_Step_0_gml_586_0")
    gml_Script_c_talk_wait()
    gml_Script_c_wait(15)
    gml_Script_c_sel(ra)
    gml_Script_c_arg_objectxy(ra_actor, 5, 0)
    gml_Script_c_setxy(x, y)
    gml_Script_c_autowalk(1)
    gml_Script_c_flip("x")
    gml_Script_c_sel(su)
    gml_Script_c_flip("x")
    gml_Script_c_autowalk(1)
    gml_Script_c_walkdirect(1453, 192, 30)
    gml_Script_c_delayfacing(31, "l")
    gml_Script_c_sel(ra)
    gml_Script_c_walkdirect(1271, 202, 25)
    gml_Script_c_delayfacing(26, "r")
    gml_Script_c_sel(no)
    gml_Script_c_autowalk(1)
    gml_Script_c_walk_wait("r", 4, 23.5)
    gml_Script_c_autodepth(1)
    gml_Script_c_walk_wait("d", 4, 5)
    gml_Script_c_walkdirect_wait(1390, 173, 10)
    gml_Script_c_sprite(215)
    gml_Script_c_halt()
    gml_Script_c_sel(kr)
    gml_Script_c_autodepth(1)
}
if (con == 20)
{
    global.flag[307] = 2
    con = 2
    alarm[0] = 30
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_autowalk(0)
    gml_Script_c_walkdirect_wait(1157, 188, 15)
    gml_Script_c_stickto(su_actor, -10)
    gml_Script_c_sel(ra)
    gml_Script_c_facing("d")
    gml_Script_c_sel(su)
    gml_Script_c_sprite(844)
    gml_Script_c_imagespeed(0)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E6* ..^1. huh? What...?/%", "obj_ch2_city07_slash_Step_0_gml_643_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(1004)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EK* Alright. Where'd the hell'd you get this?/", "obj_ch2_city07_slash_Step_0_gml_650_0")
    gml_Script_c_facenext("ralsei", "2")
    gml_Script_c_msgnextloc("\\E2* Perhaps they won it at that orb-tossing game./%", "obj_ch2_city07_slash_Step_0_gml_652_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(1000)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E2* Yeah^1, like Kris could ever win that!^1! Hahaha!!/", "obj_ch2_city07_slash_Step_0_gml_662_0")
    gml_Script_c_msgnextloc("\\EA* They musta stole it or something!^1! Haha!!/%", "obj_ch2_city07_slash_Step_0_gml_663_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_autowalk(0)
    gml_Script_c_imageindex(1)
    gml_Script_c_imagespeed(0)
    gml_Script_c_sprite(788)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\EL* S..^1. Stole it...?/%", "obj_ch2_city07_slash_Step_0_gml_673_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(787)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E2* Wow^1, they must have really wanted to give it to you!/%", "obj_ch2_city07_slash_Step_0_gml_680_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_imagespeed(0)
    gml_Script_c_wait(30)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E6* .../%", "obj_ch2_city07_slash_Step_0_gml_689_0")
    gml_Script_c_talk_wait()
    gml_Script_c_wait(30)
    gml_Script_c_autowalk(0)
    gml_Script_c_imageindex(0)
    gml_Script_c_imagespeed(0)
    gml_Script_c_sprite(1003)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EK* Well^1, takes guts to do something stupid like that./%", "obj_ch2_city07_slash_Step_0_gml_701_0")
    gml_Script_c_talk_wait()
    gml_Script_c_facing("u")
    gml_Script_c_wait(30)
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_var_instance(gi_actor, "depth", (su_actor + 100))
    gml_Script_c_var_lerp_instance(gi_actor, "y", 188, 176, 3)
    gml_Script_c_wait(3)
    gml_Script_c_var_lerp_instance(gi_actor, "y", 176, 236, 8)
    gml_Script_c_wait(8)
    gml_Script_c_soundplay(172)
    gml_Script_c_var_instance(gi_actor, "visible", 0)
    gml_Script_c_wait(50)
    gml_Script_c_sel(su)
    gml_Script_c_sprite(230)
    gml_Script_c_setxy(1169, 273)
    gml_Script_c_shakeobj()
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E2* ..^1. Don't think I'm gonna let you out-do me!/%", "obj_ch2_city07_slash_Step_0_gml_727_0")
    gml_Script_c_talk_wait()
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EQ* If you're gonna pull some stupid stunt like that.../%", "obj_ch2_city07_slash_Step_0_gml_731_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("r")
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_sprite(1004)
    gml_Script_c_setxy(1159, 218)
    gml_Script_c_pannable(1)
    gml_Script_c_pan(1074, 0, 15)
    gml_Script_c_walkdirect_wait(1374, 222, 15)
    gml_Script_c_sel(kr)
    gml_Script_c_facing("r")
    gml_Script_c_sel(ra)
    gml_Script_c_facing("r")
    gml_Script_c_wait(5)
    gml_Script_c_sel(su)
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(43)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E5* Then I'll steal you something too!!/%", "obj_ch2_city07_slash_Step_0_gml_759_0")
    gml_Script_c_talk_wait()
    gml_Script_c_autowalk(1)
    gml_Script_c_walkdirect_wait(1404, 152, 10)
    gml_Script_c_facing("u")
    gml_Script_c_wait(5)
    gml_Script_c_soundplay(60)
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(152)
    gml_Script_c_imageindex(0)
    gml_Script_c_imagespeed(0)
    gml_Script_c_wait(5)
    gml_Script_c_imageindex(1)
    gml_Script_c_sel(no)
    gml_Script_c_shakeobj()
    gml_Script_c_sprite(716)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E7* Cool box.../%", "obj_ch2_city07_slash_Step_0_gml_786_0")
    gml_Script_c_talk_wait()
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\EF* A.../", "obj_ch2_city07_slash_Step_0_gml_793_0")
    gml_Script_c_msgnextloc("\\EE* AHHHH!!!/%", "obj_ch2_city07_slash_Step_0_gml_794_0")
    gml_Script_c_talk_wait()
    gml_Script_c_var_instance(boxhead, "x", 1410)
    gml_Script_c_var_instance(boxhead, "depth", 0)
    gml_Script_c_var_lerp_instance(boxhead, "y", 140, -100, 10)
    gml_Script_c_sel(su)
    gml_Script_c_sprite(995)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E6* N..^1. Noelle!?/%", "obj_ch2_city07_slash_Step_0_gml_806_0")
    gml_Script_c_talk_wait()
    gml_Script_c_wait(30)
    gml_Script_c_sel(su)
    gml_Script_c_autowalk(1)
    gml_Script_c_autofacing(0)
    gml_Script_c_sprite(821)
    gml_Script_c_walkdirect(1453, 192, 10)
    gml_Script_c_sel(ra)
    gml_Script_c_autowalk(1)
    gml_Script_c_walkdirect(1271, 202, 20)
    gml_Script_c_delayfacing(21, "r")
    gml_Script_c_sel(no)
    gml_Script_c_autowalk(1)
    gml_Script_c_walk_wait("r", 4, 23.6)
    gml_Script_c_autodepth(1)
    gml_Script_c_walk_wait("d", 4, 5)
    gml_Script_c_walkdirect_wait(1390, 173, 10)
    gml_Script_c_sprite(215)
    gml_Script_c_halt()
    gml_Script_c_sel(kr)
    gml_Script_c_autodepth(1)
}
if (con == 30)
{
    global.flag[307] = 3
    con = 2
    alarm[0] = 30
    gml_Script_c_pannable(1)
    gml_Script_c_pan(1074, 0, 20)
    gml_Script_c_sel(kr)
    gml_Script_c_walkdirect_wait(1328, 172, 24)
    gml_Script_c_facing("r")
    gml_Script_c_var_instance(boxhead, "x", no_actor.x)
    gml_Script_c_var_instance(boxhead, "y", no_actor.y)
    gml_Script_c_var_instance(boxhead, "visible", 1)
    gml_Script_c_wait(15)
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\E2* K..^1. Kris...? Y..^1. You have something for me...?/%", "obj_ch2_city07_slash_Step_0_gml_860_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_var_lerp_instance(gi_actor, "x", 1321, 1375, 15)
    gml_Script_c_var_lerp_instance(gi_actor, "y", 127, 110, 15)
    gml_Script_c_autodepth(0)
    gml_Script_c_depth(0)
    gml_Script_c_wait(15)
    gml_Script_c_depth(-10)
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\E4* (Kris hasn't given me a gift like this...)/", "obj_ch2_city07_slash_Step_0_gml_873_0")
    gml_Script_c_msgnextloc("\\E9* (Since we were little kids.)/", "obj_ch2_city07_slash_Step_0_gml_874_0")
    gml_Script_c_msgnextloc("\\E6* (Are they saying they want things to go back to...)/", "obj_ch2_city07_slash_Step_0_gml_875_0")
    gml_Script_c_msgnextloc("\\E8* W-wait^1, isn't that the plush I just gave Queen!?/", "obj_ch2_city07_slash_Step_0_gml_876_0")
    gml_Script_c_msgnextloc("\\E8* What!? You want a refund!? So you can...!?/%", "obj_ch2_city07_slash_Step_0_gml_877_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(no)
    gml_Script_c_sprite(154)
    gml_Script_c_var_lerp_instance(gi_actor, "y", 97, -100, 10)
    gml_Script_c_var_lerp_instance(boxhead, "y", no_actor.y, -100, 10)
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\E8* Come on^1, say that to my face!^1! Gosh!!/%", "obj_ch2_city07_slash_Step_0_gml_888_0")
    gml_Script_c_talk_wait()
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("d")
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(1507)
    gml_Script_c_sel(su)
    gml_Script_c_flip("x")
    gml_Script_c_sprite(995)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E6* N..^1. Noelle!?/%", "obj_ch2_city07_slash_Step_0_gml_903_0")
    gml_Script_c_talk_wait()
    gml_Script_c_wait(15)
    gml_Script_c_sel(ra)
    gml_Script_c_setxy(1229, 200)
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("r")
    gml_Script_c_sel(su)
    gml_Script_c_flip("x")
    gml_Script_c_setxy(1159, 218)
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("r")
    gml_Script_c_sel(kr)
    gml_Script_c_walkdirect(1301, 234, 20)
    gml_Script_c_delayfacing(21, "r")
    gml_Script_c_sel(su)
    gml_Script_c_walkdirect(1453, 192, 20)
    gml_Script_c_delayfacing(21, "l")
    gml_Script_c_sel(ra)
    gml_Script_c_walkdirect(1271, 202, 20)
    gml_Script_c_delayfacing(21, "r")
    gml_Script_c_sel(no)
    gml_Script_c_autowalk(1)
    gml_Script_c_walk_wait("r", 4, 23.6)
    gml_Script_c_autodepth(1)
    gml_Script_c_walk_wait("d", 4, 5)
    gml_Script_c_walkdirect_wait(1390, 173, 10)
    gml_Script_c_sprite(215)
    gml_Script_c_halt()
    gml_Script_c_sel(kr)
    gml_Script_c_autodepth(1)
}
if (con == 40)
{
    global.flag[307] = 4
    con = 2
    alarm[0] = 30
    berdlygift = 1
    gml_Script_c_pannable(1)
    gml_Script_c_pan(1074, 0, 40)
    gml_Script_c_sel(be)
    gml_Script_c_walkdirect_wait(1522, 229, 40)
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E0* Kris^1, have you seen.../%", "obj_ch2_city07_slash_Step_0_gml_961_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(kr)
    gml_Script_c_facing("r")
    gml_Script_c_sel(be)
    gml_Script_c_sprite(163)
    gml_Script_c_emote("!", 30, 5)
    gml_Script_c_shakeobj()
    gml_Script_c_sel(su)
    gml_Script_c_emote("!", 30)
    gml_Script_c_sel(ra)
    gml_Script_c_emote("!", 30)
    gml_Script_c_wait(30)
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E3* Kris!^1? We took a break from trucing for ONE second.../", "obj_ch2_city07_slash_Step_0_gml_982_0")
    gml_Script_c_msgnextloc("\\EB* And you're ALREADY back with Susie?!/", "obj_ch2_city07_slash_Step_0_gml_984_0_b")
    gml_Script_c_facenext("susie", "K")
    gml_Script_c_msgnextloc("\\EK* ???????/%", "obj_ch2_city07_slash_Step_0_gml_984_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(be)
    gml_Script_c_facing("r")
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\EH* Should have expected this..^1. hmph.../%", "obj_ch2_city07_slash_Step_0_gml_991_0")
    gml_Script_c_talk_wait()
    gml_Script_c_facing("l")
    gml_Script_c_shakeobj()
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E2* You couldn't keep up with my puzzle-solving skills!/%", "obj_ch2_city07_slash_Step_0_gml_998_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(kr)
    gml_Script_c_walkdirect_wait(1478, 234, 30)
    gml_Script_c_wait(15)
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_var_lerp("x", 1470, 1527, 15)
    gml_Script_c_wait(16)
    gml_Script_c_stickto(be_actor, -10)
    gml_Script_c_wait(10)
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E3* H..^1. huh...?/%", "obj_ch2_city07_slash_Step_0_gml_1017_0")
    gml_Script_c_talk_wait()
    gml_Script_c_var_instance(id, "present_transform", 1)
    gml_Script_c_soundplay(45)
    gml_Script_c_wait(5)
    gml_Script_c_sel(gi)
    gml_Script_c_sprite(137)
    gml_Script_c_wait(60)
    gml_Script_c_msgsetloc(0, "\\E5* A plush...? Of ..^1. me?/", "obj_ch2_city07_slash_Step_0_gml_1018_0")
    gml_Script_c_msgnextloc("\\E4* With..^1. nipples?/%", "obj_ch2_city07_slash_Step_0_gml_1019_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(be)
    gml_Script_c_facing("r")
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_flip("x")
    gml_Script_c_addxy(-6, 0)
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\EE* ..^1. Hmph. Guess I'll forgive you for now./%", "obj_ch2_city07_slash_Step_0_gml_1026_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(be)
    gml_Script_c_facing("l")
    gml_Script_c_sel(gi)
    gml_Script_c_flip("x")
    gml_Script_c_addxy(6, 0)
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E1* See you^1, Kris./%", "obj_ch2_city07_slash_Step_0_gml_1033_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(gi)
    gml_Script_c_flip("x")
    gml_Script_c_addxy(-6, 0)
    gml_Script_c_stickto(be_actor, -10)
    gml_Script_c_sel(be)
    gml_Script_c_walkdirect((gml_Script_camerax() + 900), 229, 40)
    gml_Script_c_wait(60)
    gml_Script_c_sel(gi)
    gml_Script_c_stickto_stop()
    gml_Script_c_wait(1)
    gml_Script_c_sel(su)
    gml_Script_c_shakeobj()
    gml_Script_c_sprite(45)
    gml_Script_c_sel(kr)
    gml_Script_c_facing("l")
    gml_Script_scr_smallface(0, "susie", 17, "left", "top", gml_Script_stringsetloc("Why the hell'd you give it to Berdly!?", "obj_ch2_city07_slash_Step_0_gml_1054_0"))
    gml_Script_scr_smallface(1, "noelle", 20, 150, "middle", gml_Script_stringsetloc("Why did you give it to Berdly!?", "obj_ch2_city07_slash_Step_0_gml_1055_0"))
    gml_Script_scr_smallface(2, "ralsei", 30, 250, "bottom", gml_Script_stringsetloc("Um, what... unexpected kindness, Kris!", "obj_ch2_city07_slash_Step_0_gml_1056_0"))
    gml_Script_c_speaker("no_one")
    gml_Script_c_msgsetloc(0, "\\f0\\f1\\f2/%", "obj_ch2_city07_slash_Step_0_gml_1059_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_facing("r")
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EC* ..^1. Let's just get the hell out of here./%", "obj_ch2_city07_slash_Step_0_gml_1067_0")
    gml_Script_c_talk_wait()
    gml_Script_c_autowalk(1)
    gml_Script_c_walk("r", 6, 30)
    gml_Script_c_wait(30)
    gml_Script_c_halt()
    gml_Script_c_sel(no)
    gml_Script_c_sprite(154)
    gml_Script_c_var_instance(boxhead, "x", no_actor.x)
    gml_Script_c_var_instance(boxhead, "y", no_actor.y)
    gml_Script_c_var_instance(boxhead, "visible", 1)
    gml_Script_c_var_lerp_instance(boxhead, "y", no_actor.y, -100, 5)
    gml_Script_c_sel(ra)
    gml_Script_c_shakeobj()
    gml_Script_c_sprite(1507)
    gml_Script_c_sel(su)
    gml_Script_c_flip("x")
    gml_Script_c_shakeobj()
    gml_Script_c_sprite(995)
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\E8* W..^1. wait!!/%", "obj_ch2_city07_slash_Step_0_gml_1096_0")
    gml_Script_c_talk_wait()
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E6* N..^1. Noelle!?/%", "obj_ch2_city07_slash_Step_0_gml_1100_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("r")
    gml_Script_c_sel(su)
    gml_Script_c_flip("x")
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("r")
    gml_Script_c_sel(no)
    gml_Script_c_facing("d")
    gml_Script_c_wait(15)
    gml_Script_c_sel(kr)
    gml_Script_c_walkdirect(1301, 234, 20)
    gml_Script_c_delayfacing(21, "r")
    gml_Script_c_sel(su)
    gml_Script_c_walkdirect(1453, 192, 20)
    gml_Script_c_delayfacing(21, "l")
    gml_Script_c_sel(ra)
    gml_Script_c_walkdirect(1271, 202, 20)
    gml_Script_c_delayfacing(21, "r")
    gml_Script_c_sel(no)
    gml_Script_c_autowalk(1)
    gml_Script_c_walk_wait("r", 4, 23.6)
    gml_Script_c_autodepth(1)
    gml_Script_c_walk_wait("d", 4, 5)
    gml_Script_c_walkdirect_wait(1390, 173, 10)
    gml_Script_c_sprite(215)
    gml_Script_c_halt()
    gml_Script_c_sel(kr)
    gml_Script_c_autodepth(1)
    gml_Script_c_wait(60)
}
if (con == 3)
{
    con = 4
    alarm[0] = 30
    gml_Script_c_sel(no)
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0)
    gml_Script_c_sprite(737)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EK* ..^1. the hell were you doing in there? That's cheating./", "obj_ch2_city07_slash_Step_0_gml_1156_0")
    gml_Script_c_facenext("noelle", "2")
    gml_Script_c_msgnextloc("\\E2* I..^1. I..^1. um..^1. I.../", "obj_ch2_city07_slash_Step_0_gml_1158_0")
    gml_Script_c_facenext("susie", "1")
    gml_Script_c_msgnextloc("\\E1* ..^1. hm. Glad you're okay though./", "obj_ch2_city07_slash_Step_0_gml_1160_0")
    gml_Script_c_msgnextloc("\\E0* Since that stupid Queen took you^1, I was kinda worried.../", "obj_ch2_city07_slash_Step_0_gml_1161_0")
    gml_Script_c_facenext("noelle", "L")
    gml_Script_c_msgnextloc("\\EL* (Thump^1, thump...)/%", "obj_ch2_city07_slash_Step_0_gml_1163_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(844)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EF* Wait./%", "obj_ch2_city07_slash_Step_0_gml_1169_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_autowalk(1)
    gml_Script_c_walkdirect_wait(1372, 229, 8)
    gml_Script_c_sprite(43)
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_sel(no)
    gml_Script_c_sprite(716)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EH* Aren't you on their side!?/", "obj_ch2_city07_slash_Step_0_gml_1184_0")
    gml_Script_c_facenext("noelle", "B")
    gml_Script_c_msgnextloc("\\EB* H-huh!?/", "obj_ch2_city07_slash_Step_0_gml_1186_0")
    gml_Script_c_msgnextloc("\\ED* W-wait^1, wait^1, wait^1, wait^1, wait!!/", "obj_ch2_city07_slash_Step_0_gml_1187_0")
    gml_Script_c_msgnextloc("\\E3* Umm^1, I..^1. I.../%", "obj_ch2_city07_slash_Step_0_gml_1188_0")
    gml_Script_c_talk_wait()
    gml_Script_c_msc(1085)
    gml_Script_c_talk_wait()
}
if (con == 11)
{
    con = 6
    alarm[0] = 30
    var arg1 = 390
    var arg2 = 47
    if jp
    {
        arg1 = 400
        arg2 = 63
    }
    gml_Script_scr_smallface(0, "noelle", 22, arg1, arg2, gml_Script_stringsetloc("Thump, thump...", "obj_ch2_city07_slash_Step_0_gml_1201_0"))
    gml_Script_c_sel(no)
    gml_Script_c_facing("d")
    gml_Script_c_sel(su)
    gml_Script_c_imagespeed(0)
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\E3* Th..^1. that's right^1! We have a truce!!/", "obj_ch2_city07_slash_Step_0_gml_1210_0")
    gml_Script_c_msgnextloc("\\E2* Kris said I could..^1. I could be on your team!/%", "obj_ch2_city07_slash_Step_0_gml_1211_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(46)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E6* Oh^1, really?/%", "obj_ch2_city07_slash_Step_0_gml_1218_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(80)
    gml_Script_c_setxy(1370, 219)
    gml_Script_c_msgsetloc(0, "\\E0* ..^1. well^1, if Kris said so^1, I guess./%", "obj_ch2_city07_slash_Step_0_gml_1225_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(82)
    gml_Script_c_msgsetloc(0, "\\E2* Didn't really wanna kill you anyway.\\f0/%", "obj_ch2_city07_slash_Step_0_gml_1231_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(826)
    gml_Script_c_wait(30)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EY* So? Get in line already./", "obj_ch2_city07_slash_Step_0_gml_1241_0")
    gml_Script_c_facenext("noelle", "M")
    gml_Script_c_msgnextloc("\\EM* O..^1. okay!!/%", "obj_ch2_city07_slash_Step_0_gml_1243_0")
    gml_Script_c_talk_wait()
}
if (con == 12)
{
    con = 6
    alarm[0] = 30
    gml_Script_c_sel(no)
    gml_Script_c_sprite(716)
    gml_Script_c_shakeobj()
    gml_Script_c_sel(kr)
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(1420)
    gml_Script_c_imagespeed(0.5)
    gml_Script_c_delaycmd(20, "imagespeed", 0)
    gml_Script_c_sel(su)
    gml_Script_c_flip("x")
    gml_Script_c_sprite(1449)
    gml_Script_c_setxy(1455, 217)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walkdirect_wait(1535, 217, 3)
    gml_Script_c_wait(5)
    gml_Script_c_sprite(1449)
    gml_Script_c_imagespeed(0)
    gml_Script_c_setxy(1535, 217)
    gml_Script_c_soundplay(139)
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\EE* Kris!!^1! What the heck are you saying!!!/%", "obj_ch2_city07_slash_Step_0_gml_1277_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(no)
    gml_Script_c_shakeobj()
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\E8* We have a truce!^1! A truce!!!/", "obj_ch2_city07_slash_Step_0_gml_1284_0")
    gml_Script_c_facenext("susie", "6")
    gml_Script_c_msgnextloc("\\E6* Huh?/%", "obj_ch2_city07_slash_Step_0_gml_1286_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(no)
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("d")
    gml_Script_c_sel(su)
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(151)
    gml_Script_c_imageindex(0)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_sel(kr)
    gml_Script_c_sprite(1410)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_wait(30)
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("r")
    gml_Script_c_sel(su)
    gml_Script_c_flip("x")
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("l")
    gml_Script_c_setxy(1479, 215)
    gml_Script_c_sel(no)
    gml_Script_c_sprite(215)
    gml_Script_c_halt()
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\E7* I..^1. I'm afraid Queen is going to find me..^1. I.../", "obj_ch2_city07_slash_Step_0_gml_1320_0")
    gml_Script_c_msgnextloc("\\E6* I thought you guys..^1. might be able to..^1. protect me.../", "obj_ch2_city07_slash_Step_0_gml_1321_0")
    gml_Script_c_facenext("susie", 6)
    gml_Script_c_msgnextloc("\\E6* Protect..^1. you?/", "obj_ch2_city07_slash_Step_0_gml_1323_0")
    gml_Script_c_facenext("noelle", "A")
    gml_Script_c_msgnextloc("\\EA* S..^1. sorry..^1. I..^1. if I'm getting in the way^1, I can.../%", "obj_ch2_city07_slash_Step_0_gml_1325_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(80)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\ED* Hey^1, look./%", "obj_ch2_city07_slash_Step_0_gml_1332_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(82)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EC* You can..^1. tag along in back or something./%", "obj_ch2_city07_slash_Step_0_gml_1339_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(79)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EA* Just..^1. don't get in our way or anything^1, okay?/", "obj_ch2_city07_slash_Step_0_gml_1346_0")
    gml_Script_c_facenext("noelle", "M")
    gml_Script_c_msgnextloc("\\EM* Of..^1. of course!!/%", "obj_ch2_city07_slash_Step_0_gml_1348_0")
    gml_Script_c_talk_wait()
}
if (con == 7)
{
    con = 8
    alarm[0] = 30
    var krisPosX = kr_actor.x
    var krisPosY = kr_actor.y
    gml_Script_c_sel(su)
    gml_Script_c_autowalk(1)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walkdirect((krisPosX - 60), (krisPosY - 15), 30)
    gml_Script_c_delayfacing(31, "r")
    gml_Script_c_sel(ra)
    gml_Script_c_walkdirect((krisPosX - 115), (krisPosY - 10), 30)
    gml_Script_c_delayfacing(31, "r")
    gml_Script_c_sel(no)
    gml_Script_c_autowalk(1)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walkdirect((krisPosX - 168), (krisPosY - 15), 30)
    gml_Script_c_delayfacing(31, "r")
    gml_Script_c_wait(60)
    gml_Script_c_sprite(215)
    gml_Script_c_halt()
    gml_Script_c_speaker("noelle")
    gml_Script_c_msgsetloc(0, "\\EM* Kris..^1. also s-said I should be..^1. behind..^1. Susie./", "obj_ch2_city07_slash_Step_0_gml_1384_0")
    gml_Script_c_facenext("susie", "K")
    gml_Script_c_msgnextloc("\\EK* Uhh..^1. well^1, if Kris said so?/%", "obj_ch2_city07_slash_Step_0_gml_1386_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_walkdirect((krisPosX - 168), (krisPosY - 10), 14)
    gml_Script_c_delayfacing(15, "r")
    gml_Script_c_sel(no)
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(724)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walkdirect((krisPosX - 115), (krisPosY - 15), 14)
    gml_Script_c_delaycmd(17, "imagespeed", 0)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E0* Let's go already./%", "obj_ch2_city07_slash_Step_0_gml_1403_0")
    gml_Script_c_talk_wait()
}
if (con == 9)
{
    con = 49
    alarm[0] = 30
    if (berdlygift == 1)
    {
        gml_Script_c_sel(be)
        gml_Script_c_walkdirect_wait(1410, 215, 30)
        gml_Script_c_speaker("berdly")
        gml_Script_c_msgsetloc(0, "\\E7* Hmph. Guess I'll join too. ..^1. but only for this room!/%", "obj_ch2_city07_slash_Step_0_gml_1419_0")
        gml_Script_c_talk_wait()
        gml_Script_c_walkdirect_wait(1084, 215, 20)
        gml_Script_c_walkdirect_wait(1084, 230, 10)
        gml_Script_c_facing("r")
        gml_Script_c_speaker("susie")
        gml_Script_c_msgsetloc(0, "\\EH* (NO ONE WAS ASKING!)/%", "obj_ch2_city07_slash_Step_0_gml_1427_0")
        gml_Script_c_talk_wait()
    }
    if (havewalker == 1)
    {
        gml_Script_c_pannable(1)
        gml_Script_c_panspeed(-5, 0, 15)
        var starXPos = (berdlygift ? 1005 : 1054)
        gml_Script_c_var_lerp_instance(starwalker, "x", 905, starXPos, 15)
        gml_Script_c_wait(31)
        gml_Script_c_speaker("no_name")
        gml_Script_c_msgsetloc(0, "* I will also            join/%", "obj_ch2_city07_slash_Step_0_gml_1439_0")
        gml_Script_c_talk_wait()
    }
    gml_Script_c_panobj(kr_actor, 15)
    gml_Script_c_wait(16)
    gml_Script_c_pannable(0)
}
if (con == 50 && (!gml_Script_d_ex()))
{
    con = 60
    gml_Script_c_actortokris()
}
if (con == 60 && (!gml_Script_i_ex(895)))
{
    con = 0
    gml_Script_scr_spellget(2, 11)
    global.plot = 95
    global.interact = 0
    global.facing = 0
    explore = 1
    gml_Script_scr_makecaterpillar(su_actor.x, su_actor.y, 2, 0)
    gml_Script_scr_makecaterpillar(no_actor.x, no_actor.y, 4, 1)
    gml_Script_scr_makecaterpillar(ra_actor.x, ra_actor.y, 3, 2)
    if berdlygift
        gml_Script_scr_makecaterpillar(be_actor.x, be_actor.y, 5, 3)
    if havewalker
    {
        var walkerpos = (berdlygift ? 4 : 3)
        gml_Script_scr_makecaterpillar(starwalker.x, starwalker.y, 6, walkerpos)
        with (starwalker)
            instance_destroy()
    }
    with (obj_actor)
        instance_destroy()
    with (obj_caterpillarchara)
        gml_Script_scr_caterpillar_interpolate()
}
if (explore && obj_mainchara.x < 50 && global.interact == 0)
{
    global.interact = 1
    wrongexit++
    if (wrongexit == 1)
    {
        gml_Script_scr_speaker("ralsei")
        gml_Script_msgsetloc(0, "\\EQ* Isn't that where we came from?/", "obj_ch2_city07_slash_Step_0_gml_1499_0")
        gml_Script_scr_anyface_next("susie", "2")
        gml_Script_msgnextloc("\\E2* Yeah^1, there isn't any cotton candy left so.../%", "obj_ch2_city07_slash_Step_0_gml_1501_0")
        gml_Script_d_make()
    }
    else
    {
        gml_Script_scr_speaker("noelle")
        gml_Script_msgsetloc(0, "\\E8* (How did Kris end up being the leader...?)/%", "obj_ch2_city07_slash_Step_0_gml_1506_0")
        gml_Script_d_make()
    }
}
if (explore && global.interact == 1 && (!gml_Script_d_ex()))
{
    obj_mainchara.x = 50
    global.facing = 1
    global.interact = 0
}
if hit_bottles
{
    hit_timer++
    if (hit_timer == 1)
    {
        gml_Script_snd_play(188)
        explosion_marker = gml_Script_instance_create(1375, 140, obj_marker)
        explosion_marker.sprite_index = spr_realisticexplosion
        explosion_marker.image_xscale = 2
        explosion_marker.image_yscale = 2
        var _temp_local_var_13 = explosion_marker
        gml_Script_scr_depth()
    }
    else
    {
        var finish = 0
        with (obj_marker)
        {
            if (sprite_index == spr_realisticexplosion && image_index >= 16)
            {
                finish = 1
                instance_destroy()
            }
        }
    }
    for (var i = 0; i < array_length_1d(bottle); i++)
    {
        if (hit_timer == 1)
        {
            bottle[i].gravity += 2
            bottle[i].gravity_direction = random_range(60, 150)
        }
        bottle[i].image_angle = (bottle[i].image_angle + (bottle[i].x <= 1390 ? 50 : -50))
    }
    if (hit_timer >= 30)
        hit_bottles = 0
}
if susie_heal
{
    heal_timer++
    if (heal_beam == self)
    {
        gml_Script_snd_play(181)
        heal_beam = gml_Script_scr_dark_marker((su_actor.x + 100), (su_actor.y + 65), 180)
        heal_beam.image_speed = 0.25
    }
    heal_beam.x += 2
    if (heal_beam.x >= 1310)
    {
        susie_heal = 0
        instance_destroy(heal_beam)
    }
}
if heal_effect
{
    heal_effect = 0
    healamt = gml_Script_instance_create(kr_actor.x, kr_actor.y, obj_dmgwriter)
    with (healamt)
    {
        delay = 4
        type = 3
    }
}
if box_remove_effect
{
    box_remove_timer++
    if (box_remove_timer == 1)
    {
        gml_Script_snd_play(61)
        fx = gml_Script_scr_dark_marker((no_actor.x + 20), no_actor.y, 2066)
        fx.image_speed = 1
        fx.depth = 0
    }
    if (box_remove_timer >= 5)
    {
        box_remove_effect = 0
        with (fx)
            instance_destroy()
    }
}
if present_transform
{
    present_transform = 0
    if (gi_actor != -4)
    {
        with (gi_actor)
            gml_Script_scr_oflash()
    }
}
