draw_set_color(c_black)
xx = (gml_Script_camerax() - 72)
yy = (gml_Script_cameray() + 88)
if gml_Script_i_ex(80)
{
    if (obj_mainchara.x <= (gml_Script_camerax() + 320))
        xx += 320
}
gml_Script_scr_darkbox_black((xx + 96), (yy + 100), (xx + 360), (yy + 220))
draw_set_color(c_white)
gml_Script_scr_84_set_draw_font("mainbig")
draw_text((xx + 120), (yy + 120), ("$" + string(global.gold)))
var roomstring = gml_Script_stringsetloc("HELD SPACE: ", "obj_moneydisplay_slash_Draw_0_gml_22_0")
var roomstring2 = gml_Script_stringsetloc("STORAGE SPACE: ", "obj_moneydisplay_slash_Draw_0_gml_23_0")
gml_Script_scr_itemcheck(0)
draw_text((xx + 120), (yy + 146), (roomstring + string(itemcount)))
gml_Script_scr_itemcheck_pocket(0)
draw_text((xx + 120), (yy + 172), (roomstring2 + string(itemcount)))
if (!gml_Script_d_ex())
    instance_destroy()
