if (con == 0 && obj_mainchara.x >= x && global.interact == 0)
{
    con = 1
    global.interact = 1
}
if (con == 1)
{
    con = 2
    cutscene_master = gml_Script_scr_cutscene_make()
    gml_Script_scr_maincharacters_actors()
    la = 5
    la_actor = gml_Script_instance_create(1220, 184, obj_actor)
    gml_Script_scr_actor_setup(la, la_actor, "lancer")
    la_actor.sprite_index = spr_lancer_ut
    gml_Script_c_sel(la)
    gml_Script_c_autowalk(0)
    nl = 6
    nl_actor = gml_Script_instance_create((obj_mainchara.x - 500), (obj_mainchara.y - 80), obj_actor)
    gml_Script_scr_actor_setup(nl, nl_actor, "lancer")
    nl_actor.sprite_index = spr_lancer_rt
    gml_Script_c_sel(nl)
    gml_Script_c_autowalk(0)
    gml_Script_snd_free_all()
}
if (con == 2)
{
    gml_Script_c_wait(15)
    gml_Script_c_sel(kr)
    gml_Script_c_emote("!", 30)
    gml_Script_c_sel(su)
    gml_Script_c_emote("!", 30)
    gml_Script_c_sel(ra)
    gml_Script_c_emote("!", 30)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E7* Hey^1, is that... Lancer!?/%", "obj_cutscene_test_slash_Step_0_gml_51_0")
    gml_Script_c_talk_wait()
    gml_Script_c_msgzurasu(1)
    gml_Script_c_pannable(1)
    gml_Script_c_panspeed(5, 0, 35)
    gml_Script_c_sel(kr)
    gml_Script_c_walkdirect(936, 240, 15)
    gml_Script_c_delayfacing(16, "r")
    gml_Script_c_sel(su)
    gml_Script_c_walkdirect(976, 186, 15)
    gml_Script_c_delayfacing(16, "r")
    gml_Script_c_sel(ra)
    gml_Script_c_walkdirect(930, 138, 15)
    gml_Script_c_delayfacing(16, "r")
    gml_Script_c_wait(16)
    gml_Script_c_msgside("bottom")
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E2* What are you up to^1, buddy?/%", "obj_cutscene_test_slash_Step_0_gml_78_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(la)
    gml_Script_c_facing("l")
    gml_Script_c_speaker("lancer")
    gml_Script_c_msgsetloc(0, "\\E1* Lancer?/%", "obj_cutscene_test_slash_Step_0_gml_87_0")
    gml_Script_c_talk_wait()
    gml_Script_c_var_lerp("image_angle", "init", 360, 30)
    gml_Script_c_soundplay(186)
    gml_Script_c_mus2("initloop", "lancer.ogg", 0)
    gml_Script_c_speaker("lancer")
    gml_Script_c_msgsetloc(0, "\\E2* Ho ho ho!!^1! Susie!!!/%", "obj_cutscene_test_slash_Step_0_gml_96_0")
    gml_Script_c_talk_wait()
    gml_Script_c_wait(60)
    gml_Script_c_mus("stop")
    gml_Script_c_mus("free_all")
    gml_Script_c_soundplay(104)
    gml_Script_c_speaker("lancer")
    gml_Script_c_msgsetloc(0, "\\E1* Who says I'm Lancer?/", "obj_cutscene_test_slash_Step_0_gml_107_0")
    gml_Script_c_facenext("susie", 0)
    gml_Script_c_msgnextloc("\\E0* Of course you're Lancer.../", "obj_cutscene_test_slash_Step_0_gml_109_0")
    gml_Script_c_facenext("lancer", 3)
    gml_Script_c_msgnextloc("\\E3* ..^1. then who's that?/%", "obj_cutscene_test_slash_Step_0_gml_111_0")
    gml_Script_c_talk_wait()
    gml_Script_c_wait(15)
    gml_Script_c_panspeed(-5, 0, 10)
    gml_Script_c_sel(nl)
    gml_Script_c_walkdirect(760, 210, 15)
    gml_Script_c_wait(30)
    gml_Script_c_sel(kr)
    gml_Script_c_facing("l")
    gml_Script_c_emote("!", 30)
    gml_Script_c_sel(su)
    gml_Script_c_facing("l")
    gml_Script_c_emote("!", 30)
    gml_Script_c_sel(ra)
    gml_Script_c_facing("l")
    gml_Script_c_emote("!", 30)
    gml_Script_c_wait(30)
    gml_Script_c_speaker("lancer")
    gml_Script_c_msgsetloc(0, "\\E1* Hoho!/%", "obj_cutscene_test_slash_Step_0_gml_139_0")
    gml_Script_c_talk_wait()
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E0* Alright^1, are you Lancer then!?/", "obj_cutscene_test_slash_Step_0_gml_145_0")
    gml_Script_c_facenext("lancer", 8)
    gml_Script_c_msgnextloc("\\E8* Yes I am!/%", "obj_cutscene_test_slash_Step_0_gml_147_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(1507)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\EL* Which one of you said that!?/%", "obj_cutscene_test_slash_Step_0_gml_156_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(la)
    gml_Script_c_spin(5)
    gml_Script_c_sel(nl)
    gml_Script_c_var_lerp("image_angle", "init", 360, 30)
    gml_Script_c_wait(30)
    gml_Script_c_sel(la)
    gml_Script_c_spin(0)
    gml_Script_c_facing("l")
    gml_Script_c_speaker("lancer")
    gml_Script_c_msgsetloc(0, "\\E1* I did!/", "obj_cutscene_test_slash_Step_0_gml_174_0")
    gml_Script_c_facenext("susie", 4)
    gml_Script_c_msgnextloc("\\E4* That's it^1, I'm taking a closer look!/%", "obj_cutscene_test_slash_Step_0_gml_176_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(la)
    gml_Script_c_facing("l")
    gml_Script_c_sel(ra)
    gml_Script_c_facing("d")
    gml_Script_c_sel(kr)
    gml_Script_c_facing("d")
    gml_Script_c_sel(su)
    gml_Script_c_walkdirect((obj_mainchara.x + 280), (obj_mainchara.y - 80), 20)
    gml_Script_c_wait(60)
    gml_Script_c_walkdirect(826, 190, 30)
    gml_Script_c_wait(60)
    gml_Script_c_walkdirect(976, 186, 30)
    gml_Script_c_delayfacing(31, "d")
    gml_Script_c_wait(60)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E0* Umm^1, so what did you figure out?/", "obj_cutscene_test_slash_Step_0_gml_209_0")
    gml_Script_c_facenext("susie", 3)
    gml_Script_c_msgnextloc("\\E3* Uhhh.../%", "obj_cutscene_test_slash_Step_0_gml_211_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(832)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E9* I'll just be friends with both of them!/%", "obj_cutscene_test_slash_Step_0_gml_220_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(812)
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E2* That's the attitude!/", "obj_cutscene_test_slash_Step_0_gml_231_0")
    gml_Script_c_facenext("lancer", 1)
    gml_Script_c_msgnextloc("\\E1* Hohoho^1! Yeah^1, it is!/%", "obj_cutscene_test_slash_Step_0_gml_233_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(la)
    gml_Script_c_sprite(2271)
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0.5)
    gml_Script_c_soundplay(188)
    gml_Script_c_wait(34)
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(1507)
    gml_Script_c_sel(su)
    gml_Script_c_sprite(996)
    gml_Script_c_sel(kr)
    gml_Script_c_facing("r")
    gml_Script_c_sel(la)
    gml_Script_c_visible(0)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\ER* What the!?/", "obj_cutscene_test_slash_Step_0_gml_259_0")
    gml_Script_c_msgnextloc("\\EZ* L-Lancer!?/%", "obj_cutscene_test_slash_Step_0_gml_260_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(kr)
    gml_Script_c_facing("l")
    gml_Script_c_sel(su)
    gml_Script_c_facing("l")
    gml_Script_c_sel(ra)
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("l")
    gml_Script_c_speaker("lancer")
    gml_Script_c_msgsetloc(0, "\\E2* That was the fake one./", "obj_cutscene_test_slash_Step_0_gml_274_0")
    gml_Script_c_facenext("ralsei", 2)
    gml_Script_c_msgnextloc("\\E2* Oh^1, okay./%", "obj_cutscene_test_slash_Step_0_gml_276_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(nl)
    gml_Script_c_walkdirect(450, 205, 15)
    gml_Script_c_wait(30)
    gml_Script_c_actortokris()
    gml_Script_c_actortocaterpillar()
    gml_Script_c_panobj(kr_actor, 10)
    gml_Script_c_wait(10)
    gml_Script_c_pannable(0)
    gml_Script_c_terminatekillactors()
}
if (con == 2 && (!gml_Script_i_ex(895)))
{
    con = 3
    global.interact = 0
    global.facing = 0
}
