if (obj_heart.x < (left - 1))
    obj_heart.x = (left - 1)
if (obj_heart.x > (right - 16))
    obj_heart.x = (right - 16)
if (obj_heart.y < (top - 1))
    obj_heart.y = (top - 1)
if (obj_heart.y > (bottom - 16))
    obj_heart.y = (bottom - 16)
