var _temp_local_var_1, _temp_local_var_6;
if (stonelancer != self)
{
    var _temp_local_var_1 = stonelancer
    gml_Script_scr_depth()
}
if (obj_mainchara.x > x && con == -1)
{
    con = 1
    global.interact = 1
    global.facing = 1
    gml_Script_scr_losechar()
    gml_Script_scr_getchar(2)
    gml_Script_scr_getchar(3)
    gml_Script_scr_makecaterpillar(1750, 240, 2, 0)
    gml_Script_scr_makecaterpillar(1750, 240, 3, 1)
    with (obj_caterpillarchara)
        visible = false
    cutscene_master = gml_Script_scr_cutscene_make()
    gml_Script_scr_maincharacters_actors()
    gml_Script_c_sel(kr)
    gml_Script_c_facing("r")
    gml_Script_c_sel(su)
    gml_Script_c_setxy(susienpc.x, susienpc.y)
    gml_Script_c_sprite(174)
    gml_Script_c_autowalk(0)
    gml_Script_c_halt()
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(190)
    gml_Script_c_autowalk(0)
    gml_Script_c_halt()
    be = 3
    be_actor = gml_Script_instance_create(340, 180, obj_actor)
    gml_Script_scr_actor_setup(be, be_actor, "berdly")
    be_actor.sprite_index = spr_berdly_walk_down_dw
    fan_a = 4
    fan_a_actor = gml_Script_instance_create(1788, 188, obj_actor)
    gml_Script_scr_actor_setup(fan_a, fan_a_actor, "fan_a")
    fan_a_actor.sprite_index = spr_npc_butler
    gml_Script_c_sel(fan_a)
    gml_Script_c_halt()
    fan_b = 5
    fan_b_actor = gml_Script_instance_create(1880, 188, obj_actor)
    gml_Script_scr_actor_setup(fan_b, fan_b_actor, "fan_b")
    fan_b_actor.sprite_index = spr_npc_butler
    gml_Script_c_sel(fan_b)
    gml_Script_c_halt()
    fan_c = 6
    fan_c_actor = gml_Script_instance_create(1733, 150, obj_actor)
    gml_Script_scr_actor_setup(fan_c, fan_c_actor, "fan_c")
    fan_c_actor.sprite_index = spr_npc_butler
    gml_Script_c_sel(fan_c)
    gml_Script_c_halt()
    fan_d = 7
    fan_d_actor = gml_Script_instance_create(1812, 150, obj_actor)
    gml_Script_scr_actor_setup(fan_d, fan_d_actor, "fan_c")
    fan_d_actor.sprite_index = spr_npc_butler
    gml_Script_c_sel(fan_d)
    gml_Script_c_halt()
    fan_e = 8
    fan_e_actor = gml_Script_instance_create(1890, 150, obj_actor)
    gml_Script_scr_actor_setup(fan_e, fan_e_actor, "fan_c")
    fan_e_actor.sprite_index = spr_npc_butler
    gml_Script_c_sel(fan_e)
    gml_Script_c_halt()
    la = 9
    la_actor = gml_Script_instance_create(1605, 255, obj_actor)
    gml_Script_scr_actor_setup(la, la_actor, "lancer")
    la_actor.sprite_index = spr_cutscene_20_lancer_desaturated
    gml_Script_c_sel(la)
    gml_Script_c_autodepth(0)
    gml_Script_c_depth(98000)
    gml_Script_c_visible(0)
    stonelancer = gml_Script_scr_dark_marker(1606, 236, 193)
    stonelancer.depth = 97000
    stonelancer.image_alpha = 0
}
if (con == 1 || gml_Script_scr_cutscene_loaded())
{
    con = 2
    alarm[0] = 30
    gml_Script_c_msgside("top")
    gml_Script_c_soundplay(198)
    gml_Script_c_sel(su)
    gml_Script_c_emote("!", 30)
    gml_Script_c_var_instance(susienpc, "visible", 0)
    gml_Script_c_wait(30)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E6* Th..^1. that screaming..^1. Ralsei...!?/%", "obj_ch2_scene20_slash_Step_0_gml_112_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(kr)
    gml_Script_c_walkdirect(1440, 247, 35)
    gml_Script_c_sel(su)
    gml_Script_c_sprite(174)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walkdirect(1490, 221, 35)
    gml_Script_c_mus2("volume", 0, 30)
    gml_Script_c_pannable(1)
    gml_Script_c_panspeed(18, 0, 30)
    gml_Script_c_wait(31)
    gml_Script_c_halt()
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\EQ* U-umm^1, you don't have to scream.../", "obj_ch2_scene20_slash_Step_0_gml_130_0")
    gml_Script_c_msgnextloc("\\E1* ..^1. Just because you like my outfit!/%", "obj_ch2_scene20_slash_Step_0_gml_131_0")
    gml_Script_c_talk_wait()
    gml_Script_c_soundplay(197)
    n = 18
    gml_Script_c_sel(ra)
    gml_Script_c_autodepth(0)
    gml_Script_c_depth(5000)
    gml_Script_c_sel(fan_a)
    gml_Script_c_sprite(1807)
    gml_Script_c_addxy(0, n)
    gml_Script_c_shakeobj()
    gml_Script_c_sel(fan_b)
    gml_Script_c_sprite(1807)
    gml_Script_c_addxy(0, n)
    gml_Script_c_shakeobj()
    gml_Script_c_sel(fan_c)
    gml_Script_c_sprite(1807)
    gml_Script_c_addxy(0, n)
    gml_Script_c_shakeobj()
    gml_Script_c_sel(fan_d)
    gml_Script_c_sprite(1807)
    gml_Script_c_addxy(0, n)
    gml_Script_c_shakeobj()
    gml_Script_c_sel(fan_e)
    gml_Script_c_sprite(1807)
    gml_Script_c_addxy(0, n)
    gml_Script_c_shakeobj()
    gml_Script_c_wait(30)
    gml_Script_c_panspeed(-4, 0, 20)
    gml_Script_c_sel(fan_a)
    gml_Script_c_flip("x")
    gml_Script_c_sprite(1224)
    gml_Script_c_addxy(0, (-n))
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walk("r", 8, 60)
    gml_Script_c_sel(fan_b)
    gml_Script_c_flip("x")
    gml_Script_c_sprite(1224)
    gml_Script_c_addxy(0, (-n))
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walk("r", 8, 60)
    gml_Script_c_sel(fan_c)
    gml_Script_c_flip("x")
    gml_Script_c_sprite(1224)
    gml_Script_c_addxy(0, (-n))
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walk("r", 8, 60)
    gml_Script_c_sel(fan_d)
    gml_Script_c_flip("x")
    gml_Script_c_sprite(1224)
    gml_Script_c_addxy(0, (-n))
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walk("r", 8, 60)
    gml_Script_c_sel(fan_e)
    gml_Script_c_flip("x")
    gml_Script_c_sprite(1224)
    gml_Script_c_addxy(0, (-n))
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walk("r", 8, 60)
    gml_Script_c_wait(15)
    gml_Script_c_sel(ra)
    gml_Script_c_autodepth(1)
    gml_Script_c_sprite(188)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walk_wait("l", 8, 5)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\EH* O-oh!^1! Kris^1, Susie!^1! Umm^1, how may I serve you...?/", "obj_ch2_scene20_slash_Step_0_gml_204_0")
    gml_Script_c_facenext("susie", "5")
    gml_Script_c_msgnextloc("\\E5* The hell are you doing!?/", "obj_ch2_scene20_slash_Step_0_gml_206_0")
    gml_Script_c_facenext("ralsei", "2")
    gml_Script_c_msgnextloc("\\E2* Umm^1, Queen didn't have a room for me^1, so..^1. err.../%", "obj_ch2_scene20_slash_Step_0_gml_208_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sprite(186)
    gml_Script_c_imagespeed(0)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E1* She made me into one of her butlers^1, instead.../%", "obj_ch2_scene20_slash_Step_0_gml_215_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walk_wait("r", 12, 8)
    gml_Script_c_sprite(200)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_wait(15)
    gml_Script_c_imagespeed(0)
    gml_Script_c_imageindex(3)
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(189)
    gml_Script_c_imagespeed(0)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EZ* Whatever!^1! Ralsei^1! Can you heal Lancer!?/", "obj_ch2_scene20_slash_Step_0_gml_234_0")
    gml_Script_c_facenext("ralsei", "C")
    gml_Script_c_msgnextloc("\\EC* O-oh!/", "obj_ch2_scene20_slash_Step_0_gml_236_0")
    gml_Script_c_facenext("lancer", "A")
    gml_Script_c_msgnextloc("\\EA* Haha..^1. it's..^1. cold.../%", "obj_ch2_scene20_slash_Step_0_gml_238_0")
    gml_Script_c_talk_wait()
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_walk("l", 3, 9)
    gml_Script_c_wait(60)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E4* ..^1. Susie.../%", "obj_ch2_scene20_slash_Step_0_gml_248_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sprite(192)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E6* .../%", "obj_ch2_scene20_slash_Step_0_gml_255_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sprite(189)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E8* I'm afraid..^1. This is something I can't heal./", "obj_ch2_scene20_slash_Step_0_gml_262_0")
    gml_Script_c_facenext("susie", "Z")
    gml_Script_c_msgnextloc("\\EZ* Wh-what?/", "obj_ch2_scene20_slash_Step_0_gml_264_0")
    gml_Script_c_facenext("ralsei", 4)
    gml_Script_c_msgnextloc("\\E4* Lancer is.../%", "obj_ch2_scene20_slash_Step_0_gml_266_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_autowalk(0)
    gml_Script_c_walk("r", 4, 5)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_delaycmd(9, "imagespeed", 0)
    gml_Script_c_sel(la)
    gml_Script_c_visible(1)
    gml_Script_c_sel(la)
    gml_Script_c_autowalk(0)
    gml_Script_c_setxy(1606, 236)
    gml_Script_c_sel(su)
    gml_Script_c_specialsprite(4)
    gml_Script_c_imagespeed(0)
    gml_Script_c_autowalk(0)
    gml_Script_c_walk("l", 5, 8)
    gml_Script_c_delaycmd(9, "imagespeed", 0)
    gml_Script_c_sel(la)
    gml_Script_c_sprite(199)
    gml_Script_c_var_lerp_instance(stonelancer, "image_alpha", 0, 1, 15)
    gml_Script_c_wait(10)
    gml_Script_c_soundplay(201)
    gml_Script_c_wait(10)
    gml_Script_c_sel(su)
    gml_Script_c_specialsprite(4)
    gml_Script_c_sel(la)
    gml_Script_c_visible(0)
    gml_Script_c_wait(60)
    gml_Script_c_sel(su)
    gml_Script_c_facing("susieunhappy")
    gml_Script_c_autowalk(1)
    gml_Script_c_autodepth(0)
    gml_Script_c_depth(95000)
    gml_Script_c_walkdirect_wait(1572, 216, 6)
    gml_Script_c_sprite(201)
    gml_Script_c_autowalk(0)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_sel(la)
    gml_Script_c_visible(0)
    gml_Script_c_var_instance(stonelancer, "visible", 0)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EZ* Lancer!? Lancer^1, hey...!!/%", "obj_ch2_scene20_slash_Step_0_gml_328_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(191)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E4* You see^1, each Dark Fountain creates a different \"world.\"/", "obj_ch2_scene20_slash_Step_0_gml_336_0")
    gml_Script_c_msgnextloc("\\E4* A \"world\" whose Darkners reflect the will of its fountain./", "obj_ch2_scene20_slash_Step_0_gml_337_0")
    if (global.lang == "ja")
        gml_Script_c_msgnextloc("\\E4＊ その世界を生み出した&　 「闇の泉」の意志を&　 受け継いだ者たちなんだよ。/", "obj_ch2_scene20_slash_Step_0_gml_375_0_b")
    gml_Script_c_msgnextloc("\\E4* But^1, though those Darkners can exist in their own worlds.../", "obj_ch2_scene20_slash_Step_0_gml_338_0")
    gml_Script_c_msgnextloc("\\E4* They might not \"belong\" if they go to another one./%", "obj_ch2_scene20_slash_Step_0_gml_339_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(203)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EC* ..^1. so can we help him!?/%", "obj_ch2_scene20_slash_Step_0_gml_346_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(189)
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\EA* Yes. There is a way./", "obj_ch2_scene20_slash_Step_0_gml_354_0")
    gml_Script_c_msgnextloc("* Castle Town's Grand Fountain is made of pure darkness./", "obj_ch2_scene20_slash_Step_0_gml_355_0")
    gml_Script_c_msgnextloc("\\EB* As long as it stays flowing^1, any Darkner can live there./", "obj_ch2_scene20_slash_Step_0_gml_356_0")
    gml_Script_c_msgnextloc("\\E2* So..^1. if we bring Lancer back to school^1, he'll be OK again./%", "obj_ch2_scene20_slash_Step_0_gml_357_0")
    gml_Script_c_talk_wait()
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "* ..^1. So we just need to get out of here^1, huh?/%", "obj_ch2_scene20_slash_Step_0_gml_365_0")
    gml_Script_c_talk_wait()
    gml_Script_c_speaker("ralsei")
    gml_Script_c_msgsetloc(0, "\\E2* Right./", "obj_ch2_scene20_slash_Step_0_gml_372_0")
    gml_Script_c_facenext("susie", "C")
    gml_Script_c_msgnextloc("\\EC* ..^1. alright./%", "obj_ch2_scene20_slash_Step_0_gml_374_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_sprite(202)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EA* Lancer^1, we'll be back for you^1, buddy.../%", "obj_ch2_scene20_slash_Step_0_gml_378_0")
    gml_Script_c_talk_wait()
    gml_Script_c_wait(30)
    gml_Script_c_sel(su)
    gml_Script_c_facing("l")
    gml_Script_c_emote("!", 30)
    gml_Script_c_autowalk(1)
    gml_Script_c_var_instance(stonelancer, "visible", 1)
    gml_Script_c_sel(ra)
    gml_Script_c_emote("!", 30)
    gml_Script_c_speaker("berdly")
    gml_Script_c_fefc(0, 0)
    gml_Script_c_msgsetloc(0, "\\EI* Your friend..^1. If we defeat Queen^1, we can save him?/%", "obj_ch2_scene20_slash_Step_0_gml_394_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(kr)
    gml_Script_c_facing("l")
    gml_Script_c_sel(su)
    gml_Script_c_facing("l")
    gml_Script_c_sel(be)
    gml_Script_c_facing("berdlyunhappy")
    gml_Script_c_setxy(1250, 230)
    gml_Script_c_walkdirect(1298, 230, 15)
    gml_Script_c_panspeed(-8, 0, 10)
    gml_Script_c_wait(30)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E0* Uh^1, yeah./%", "obj_ch2_scene20_slash_Step_0_gml_414_0")
    gml_Script_c_talk_wait()
    gml_Script_c_facing("d")
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "* With me out of the way^1, Queen.../%", "obj_ch2_scene20_slash_Step_0_gml_421_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(be)
    gml_Script_c_sprite(682)
    gml_Script_c_halt()
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\EG* ..^1. is going to force Noelle to do her bidding./", "obj_ch2_scene20_slash_Step_0_gml_431_0")
    gml_Script_c_msgnextloc("\\E9* And if Noelle doesn't want to.../", "obj_ch2_scene20_slash_Step_0_gml_432_0")
    gml_Script_c_msgnextloc("\\E8* ..^1. She might make her face into a robot one./", "obj_ch2_scene20_slash_Step_0_gml_433_0")
    gml_Script_c_facenext("susie", "0")
    gml_Script_c_msgnextloc("\\E0* .../%", "obj_ch2_scene20_slash_Step_0_gml_435_0")
    gml_Script_c_talk_wait()
    gml_Script_c_facing("berdlyunhappy")
    gml_Script_c_walkdirect(1505, 230, 40)
    gml_Script_c_panspeed(4, 0, 15)
    gml_Script_c_wait(20)
    gml_Script_c_sel(kr)
    gml_Script_c_facing("r")
    gml_Script_c_wait(20)
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E8* Susie.../%", "obj_ch2_scene20_slash_Step_0_gml_451_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_facing("d")
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E9* Could you..^1. assist me in saving Noelle?/", "obj_ch2_scene20_slash_Step_0_gml_458_0")
    gml_Script_c_facenext("susie", "6")
    gml_Script_c_msgnextloc("\\E6* ..^1. huh...? M-me?/%", "obj_ch2_scene20_slash_Step_0_gml_460_0")
    gml_Script_c_talk_wait()
    gml_Script_c_facing("l")
    gml_Script_c_sel(be)
    gml_Script_c_sprite(682)
    gml_Script_c_halt()
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E9* I..^1. just can't do it by myself./%", "obj_ch2_scene20_slash_Step_0_gml_472_0")
    gml_Script_c_talk_wait()
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(683)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\EI* But if you can help me..^1. I have a plan./", "obj_ch2_scene20_slash_Step_0_gml_482_0")
    gml_Script_c_facenext("susie", "K")
    gml_Script_c_msgnextloc("\\EK* A plan?/%", "obj_ch2_scene20_slash_Step_0_gml_484_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(be)
    gml_Script_c_facing("berdly")
    gml_Script_c_autowalk(1)
    gml_Script_c_facing("d")
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E0* I remember from Queen's tour of this place.../", "obj_ch2_scene20_slash_Step_0_gml_493_0")
    gml_Script_c_msgnextloc("\\E0* There's a secret shortcut on the third floor./%", "obj_ch2_scene20_slash_Step_0_gml_494_0")
    gml_Script_c_talk_wait()
    gml_Script_c_facing("l")
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E1* While Kris is distracting Queen^1,/", "obj_ch2_scene20_slash_Step_0_gml_500_0")
    gml_Script_c_msgnextloc("\\E0* Susie will take the shortcut to reach Noelle^1,/%", "obj_ch2_scene20_slash_Step_0_gml_501_0")
    gml_Script_c_talk_wait()
    gml_Script_c_facing("d")
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E0* And transfer her to me on the roof./", "obj_ch2_scene20_slash_Step_0_gml_507_0")
    gml_Script_c_msgnextloc("\\E1* From there^1, I'll bring her to a safe hiding spot.../%", "obj_ch2_scene20_slash_Step_0_gml_508_0")
    gml_Script_c_talk_wait()
    gml_Script_c_autowalk(0)
    gml_Script_c_sprite(683)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\EI* And together^1, we can all defeat Queen!/%", "obj_ch2_scene20_slash_Step_0_gml_516_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_facing("u")
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E0* .../%", "obj_ch2_scene20_slash_Step_0_gml_523_0")
    gml_Script_c_talk_wait()
    gml_Script_c_facing("l")
    gml_Script_c_sel(be)
    gml_Script_c_facing("r")
    gml_Script_c_halt()
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\EK* Alright^1, sure. We'll give it a shot./", "obj_ch2_scene20_slash_Step_0_gml_534_0")
    gml_Script_c_facenext("berdly", "6")
    gml_Script_c_msgnextloc("\\E6* Haha^1! Most excellent!^1! Then.../%", "obj_ch2_scene20_slash_Step_0_gml_536_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_autodepth(1)
    gml_Script_c_sel(be)
    gml_Script_c_autowalk(1)
    gml_Script_c_walk_wait("d", 6, 5)
    gml_Script_c_walk("r", 12, 25)
    gml_Script_c_delayfacing(46, "l")
    gml_Script_c_wait(15)
    gml_Script_c_sel(kr)
    gml_Script_c_facing("r")
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(190)
    gml_Script_c_sel(su)
    gml_Script_c_facing("r")
    gml_Script_c_wait(30)
    gml_Script_c_speaker("berdly")
    gml_Script_c_msgsetloc(0, "\\E7* See you on the roof^1, fellow agent!/%", "obj_ch2_scene20_slash_Step_0_gml_563_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(be)
    gml_Script_c_walk("r", 10, 30)
    gml_Script_c_panobj(kr_actor, 30)
    gml_Script_c_wait(15)
    gml_Script_c_sel(su)
    gml_Script_c_facing("l")
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(188)
    gml_Script_c_wait(15)
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E2* Alright^1, let's go!/%", "obj_ch2_scene20_slash_Step_0_gml_583_0")
    gml_Script_c_talk_wait()
    gml_Script_c_sel(su)
    gml_Script_c_walkdirect(1360, 230, 25)
    gml_Script_c_delayfacing(26, "r")
    gml_Script_c_sel(ra)
    gml_Script_c_autowalk(0)
    gml_Script_c_walkdirect(1290, 242, 25)
    gml_Script_c_imagespeed(0.25)
    gml_Script_c_delaycmd(26, "imagespeed", 0)
    gml_Script_c_delaycmd(26, "sprite", 190)
    gml_Script_c_wait(60)
    gml_Script_c_sel(su)
    gml_Script_c_facing("l")
    gml_Script_c_speaker("susie")
    gml_Script_c_msgsetloc(0, "\\E5* ..^1. would you take that off already!?/", "obj_ch2_scene20_slash_Step_0_gml_607_0")
    gml_Script_c_facenext("ralsei", "Q")
    gml_Script_c_msgnextloc("\\EQ* S-sorry!/%", "obj_ch2_scene20_slash_Step_0_gml_609_0")
    gml_Script_c_talk_wait()
    gml_Script_c_wait(16)
    gml_Script_c_soundplay(154)
    gml_Script_c_sel(kr)
    gml_Script_c_spin(2)
    gml_Script_c_sel(su)
    gml_Script_c_spin(2)
    gml_Script_c_sel(ra)
    gml_Script_c_addxy(0, -5)
    gml_Script_c_spin(2)
    gml_Script_c_wait(16)
    gml_Script_c_soundplay(39)
    gml_Script_c_sel(kr)
    gml_Script_c_sprite(860)
    gml_Script_c_addxy(-2, -2)
    gml_Script_c_spin(0)
    gml_Script_c_sel(su)
    gml_Script_c_sprite(832)
    gml_Script_c_addxy(2, 2)
    gml_Script_c_spin(0)
    gml_Script_c_sel(ra)
    gml_Script_c_sprite(789)
    gml_Script_c_addxy(-10, 0)
    gml_Script_c_spin(0)
    gml_Script_c_mus2("volume", 1, 15)
    gml_Script_c_wait(15)
}
if (con == 3 && (!gml_Script_d_ex()))
{
    con = 4
    gml_Script_c_pannable(0)
    gml_Script_c_actortokris()
    gml_Script_c_actortocaterpillar()
    gml_Script_c_terminatekillactors()
}
if (con == 4 && (!gml_Script_i_ex(895)))
{
    con = 0
    global.interact = 0
    global.facing = 0
    global.plot = 120
    lancernpc = gml_Script_instance_create(stonelancer.x, stonelancer.y, obj_pushable_lancer)
    var _temp_local_var_6 = stonelancer
    instance_destroy()
}
