scr_remapvalue = method(-1, gml_Script_scr_remapvalue)
method(-1, gml_Script_scr_remapvalue)
remap = method(-1, gml_Script_remap)
method(-1, gml_Script_remap)
remap_clamped = method(-1, gml_Script_remap_clamped)
method(-1, gml_Script_remap_clamped)
