init = false
red_damage[0] = 0
red_target[0] = 0
shockwave_color = c_red
red_count = 0
blue_count = 0
yellow_count = 0
allowAll = true
shockwave_x_1 = -999
shockwave_x_2 = -999
bird_count = 0
bird_color[0] = c_red
platter_side = choose(1, -1)
platter_offset = irandom(29)
