event_inherited()
usprite = spr_queen_chair_swish_wine
rsprite = spr_queen_chair_swish_wine
dsprite = spr_queen_chair_swish_wine
lsprite = spr_queen_chair_swish_wine
name = "queen"
fakey = -80
yoff = 0
float = false
floaty = 0
shadow = 0
floatsiner = 0
image_speed = 0.1
fakeshadow = scr_dark_marker(x, y, sprite_index)
fakeshadow.depth = 500000
fakeshadow.image_xscale = 2
fakeshadow.visible = false
fakeshadow.image_yscale = 0.25
fakeshadow.image_speed = 0
specialsprite[0] = spr_queen_chair_ohoho_1
specialsprite[1] = spr_queen_chair_swish_wine
