angle = 0
throwcon = 1
angledraw = 1
image_xscale = 2
image_yscale = 2
radius = 300
anglespeed = 2
kx = (184 + camerax())
ky = (170 + cameray())
lx = camerax()
ly = cameray()
krisyoff[999] = 0
krisgrav = 1
fro = 0
mypower = 15
maxpower = 30
mypower = maxpower
minpower = 15
powerdir = 1
powerspeed = 0.6
throwready = 0
throwalpha = 0
activatethrow = false
throwXcon = 0
throwXtimer = 0
ralseiy = 50
