berdlytalk = 69
noelletalk = 76
scr_enemy_object_init()
default_talkmax = 90
talkmax = 90
image_speed = 0.16666666666666666
sideb_route = scr_sideb_get_phase() > 0
idlesprite = (sideb_route ? spr_berdlyb_idle_serious : spr_berdlyb_idle)
hurtsprite = spr_berdly_shocked_left_battle
sparedsprite = spr_berdly_hurt_kneel_battle
difficulty = 1
kact_count = 0
spill = 0
nact_count = 0
naction_count = 0
hurt_noelle = 0
hurt_noelle_talk = 0
noelle_hp_start = global.hp[4]
bulletoverride = -1
kris_defeat_talk = 0
kris_defeat_con = 0
balloon_con = 0
wirewait = 0
summoning = 0
freezable = false
mercy_add_amount = 0
berdly_last_line = ""
sidebcon = 0
snowgrave_con = 0
snowgrave_counter = 0
attack_phase = 0
chosenattack = 0
talkcon = 0
summontimer = 0
rr = 0
endbattle = 0
