type = 0
init = false
con = 0
actor = -1
spam_car = room == room_dw_mansion_b_east
default_sprite_front = (spam_car ? spr_sneo_car_front : spr_kris_coaster_front)
default_sprite_back = (spam_car ? spr_sneo_car_back : spr_kris_coaster_back)
hurt_sprite_front = (spam_car ? spr_sneo_car_front : spr_kris_coaster_hurt_front)
hurt_sprite_back = (spam_car ? spr_sneo_car_back : spr_kris_coaster_hurt_back)
hurt_character_sprite = spr_krisb_hurt
character_sprite = spr_krisr_dark
character_offset_x = 0
character_offset_y = 0
character_speed = 0.25
image_speed = 1
coaster_offset_x = -25
coaster_offset_y = 40
hurt = false
siner = 0
stop_siner = 0
target_x = 0
target_x_end = 0
animate = 0
siner0 = 0
siner_add0 = 0
siner_amplitude0 = 10
siner_direction0 = 0
siner_type0 = "sin"
siner_visual0 = 1
sinerx = 0
sinery = 0
battlecoasterx = 0
