depth = (obj_queen_enemy.depth - 100)
image_blend = c_green
image_alpha = 0.9
image_xscale = 0.1
image_yscale = 0.1
image_angle = 0
image_speed = 0
x += 34
y += 140
appeartimer = 0
siner = 0
con = 0
createeffect = 0
timer = 0
turn = 0
shieldsiner = 0
shieldstate = 0
shieldtimer = 0
appearcon = 0
queenhandx = 510
queenhandy = 115
idealx = x
shieldhurt = 0
shieldhurttimer = 0
shieldx = 0
shieldy = 0
shieldalpha = 1
shieldheight = sprite_get_height(sprite_index)
shieldhpgradual = 0
imabouttobreak = 0
imabouttobreak_alpha = 0.4
imabouttobreak_siner = 0
shaketimer = 0
shieldsize = obj_queen_enemy.shieldsize
for (i = 0; i < 14; i++)
{
    shieldpiece_x_origin[i] = (x + 40)
    shieldpiece_y_origin[i] = (y + 145)
    shieldpiece_x[i] = (x + 40)
    shieldpiece_y[i] = (y + 145)
    shieldpiece_xscale[i] = 2
    shieldpiece_yscale[i] = 2
    shieldpiece_alpha[i] = IMAGE_LOGO_CENTER
    shieldpiece_sprite_index[i] = spr_queenshield_pieces
    shieldpiece_image_index[i] = 0
}
