event_inherited()
mode = 1
riseSpeed = 6
riseSpeedInitial = 2
riseSpeedBoostFriction = 0.25
riseSpeedBoost = 0
riseSpeedBoostMax = 15
riseSpeedReverse = 12
spinSpeed = 6
endY = (ystart - 100)
jumpOutDuration = 20
jumpInDuration = 20
holdHeight = -1
holdDistance = 0
camFollow = 1
camFollowAfter = 0
specialEnding = undefined
startOffset = undefined
endPos[0] = [undefined, undefined]
endPos[1] = [undefined, undefined]
endPos[2] = [undefined, undefined]
startPos[0] = [undefined, undefined]
startPos[1] = [undefined, undefined]
startPos[2] = [undefined, undefined]
centerX = 1
centerY = 0
returnOnFinish = 0
fadeOutOthers = 0
bulletsApplyToAll = 0
scoreboardExists = 0
scoreboardGoal = 10
tutorialRide = 0
regenerateBullets = 1
camTargetHeightNormal = 350
camTargetHeightReverse = 240
uniqueBulletPattern = -1
uniqueRideExperience = undefined
jumpToRide = -4
