scr_bullet_init()
timer = 0
con = 0
times = 1
maxtimes = 1
bullettimer = 0
bullettimermax = 3
circle1alpha = 0
circle1radius = 31
circle1width = 2
circle1color = 16776960
circle2alpha = 0
circle2radius = 51
circle2width = 4
angleoffset = 0
bullettype = 0
depth = (obj_heart.depth + 1)
alarm[0] = 1
heartdir = point_direction(x, y, obj_heart.x, obj_heart.y)
