if (con == -1)
{
    con = 1
    global.interact = 1
    global.facing = 1
    cutscene_master = scr_cutscene_make()
    scr_maincharacters_actors()
    c_sel(kr)
    c_visible(0)
    su = (actor_count + 1)
    su_actor = instance_create(280, 220, obj_actor)
    scr_actor_setup(su, su_actor, "susie")
    su_actor.sprite_index = spr_susie_walk_back_arm
    no = (actor_count + 2)
    no_actor = instance_create(230, 220, obj_actor)
    scr_actor_setup(no, no_actor, "noelle")
    no_actor.sprite_index = spr_noelle_walk_right_dw
    be = (actor_count + 3)
    be_actor = instance_create(380, (cameray() - 200), obj_actor)
    scr_actor_setup(be, be_actor, "berdly")
    be_actor.sprite_index = spr_berdly_walk_left_dw
    cutscene_master.save_object[0] = id
}
if (con == 1)
{
    con = 49
    alarm[0] = 30
    c_msgside("bottom")
    c_var_lerp_instance(blackall, "image_alpha", 1, 0, 30)
    c_wait(30)
    c_msgside("top")
    c_speaker("susie")
    c_msgsetloc(0, "\\EL* Well^1, that wasn't too bad./", "obj_ch2_scene23d_slash_Step_0_gml_52_0")
    c_facenext("noelle", "4")
    c_msgnextloc("\\E4* Y..^1. yeah./%", "obj_ch2_scene23d_slash_Step_0_gml_54_0")
    c_talk_wait()
    c_sel(no)
    c_autowalk(false)
    c_sprite(spr_cutscene_23b_noelle_blush)
    c_imagespeed(0)
    c_imageindex(1)
    c_speaker("noelle")
    c_msgsetloc(0, "\\E9* ..^1. sigh./%", "obj_ch2_scene23d_slash_Step_0_gml_64_0")
    c_talk_wait()
    c_sel(su)
    c_facing("l")
    c_speaker("susie")
    c_msgsetloc(0, "\\E0* ...?/", "obj_ch2_scene23d_slash_Step_0_gml_71_0")
    c_facenext("noelle", 6)
    c_msgnextloc("\\E6* If only I could dream like this every day.../%", "obj_ch2_scene23d_slash_Step_0_gml_73_0")
    c_talk_wait()
    c_wait(30)
    c_sel(su)
    c_facing("u")
    c_speaker("susie")
    c_msgsetloc(0, "\\E0* Maybe.../", "obj_ch2_scene23d_slash_Step_0_gml_83_0")
    c_msgnextloc("\\EK* It..^1. doesn't have to be a dream. Y'know?/%", "obj_ch2_scene23d_slash_Step_0_gml_84_0")
    c_talk_wait()
    c_sel(no)
    c_autowalk(true)
    c_facing("r")
    c_speaker("noelle")
    c_msgsetloc(0, "\\E2* Susie...?/", "obj_ch2_scene23d_slash_Step_0_gml_92_0")
    c_facenext("susie", "K")
    c_msgnextloc("\\EK* Maybe..^1. maybe someday we could.../%", "obj_ch2_scene23d_slash_Step_0_gml_94_0")
    c_talk_wait()
    c_var_instance(id, "release_berdly", 1)
    c_wait(30)
    c_mus("free_all")
    c_mus2("initplay", "berdly_descend.ogg", 0)
    c_mus2("pitch", 0.7, 0)
    c_wait(30)
    c_sel(no)
    c_sprite(spr_noelle_shocked_dw)
    c_sel(su)
    c_sprite(spr_susie_shock_r)
    c_wait(160)
    c_wait(30)
    c_sel(su)
    c_facing("r")
    c_sel(no)
    c_facing("r")
    c_mus("free")
    c_mus2("initloop", "berdly_theme.ogg", 0)
    c_speaker("berdly")
    c_msgsetloc(0, "\\E6* Noelle^1! My lady!^1! The Cavalry has arrived to rescue you!!/%", "obj_ch2_scene23d_slash_Step_0_gml_129_0")
    c_talk_wait()
    c_facing("u")
    c_speaker("noelle")
    c_msgsetloc(0, "\\EH* (Oh^1, the good part of the dream is over.)/%", "obj_ch2_scene23d_slash_Step_0_gml_136_0")
    c_talk_wait()
    c_sel(su)
    c_facing("l")
    c_sel(no)
    c_facing("r")
    c_speaker("susie")
    c_msgsetloc(0, "\\E5* It's fine!!^1! Berdly's gonna help!^1! We're allies!!/%", "obj_ch2_scene23d_slash_Step_0_gml_147_0")
    c_talk_wait()
    c_sel(su)
    c_facing("r")
    c_var_instance(id, "hide_berdly", 1)
    c_sel(be)
    c_setxy(380, 230)
    c_autowalk(true)
    c_walk("l", 6, 8)
    c_speaker("berdly")
    c_msgsetloc(0, "\\EJ* Yes!^1! Don't worry^1, Noelle!^1! I'm stupid now!!/", "obj_ch2_scene23d_slash_Step_0_gml_159_0")
    c_facenext("noelle", "2")
    c_msgnextloc("\\E2* .../%", "obj_ch2_scene23d_slash_Step_0_gml_161_0")
    c_talk_wait()
    c_sel(su)
    c_facing("l")
    c_speaker("susie")
    c_msgsetloc(0, "\\E5* (He's good!!!)/%", "obj_ch2_scene23d_slash_Step_0_gml_170_0")
    c_talk_wait()
    c_sel(su)
    c_walkdirect_wait(280, 246, 10)
    c_wait(15)
    c_facing("u")
    c_sel(no)
    c_facing("d")
    c_sel(be)
    c_facing("d")
    c_speaker("susie")
    c_msgsetloc(0, "\\E2* Look^1, I gotta go save the day now^1, alright?/", "obj_ch2_scene23d_slash_Step_0_gml_189_0")
    c_facenext("noelle", 23)
    c_msgnextloc("\\EN* H..^1. huh!? Umm..^1. good luck^1, Susie!!/%", "obj_ch2_scene23d_slash_Step_0_gml_191_0")
    c_talk_wait()
    c_sel(su)
    c_facing("d")
    c_speaker("susie")
    c_msgsetloc(0, "\\EL* Alright^1, nugget boy. it's up to you now./", "obj_ch2_scene23d_slash_Step_0_gml_199_0")
    c_facenext("berdly", "E")
    c_msgnextloc("\\EE* Leave it to me^1, my dear Susan./", "obj_ch2_scene23d_slash_Step_0_gml_201_0")
    c_facenext("susie", "K")
    c_msgnextloc("\\EK* Yeah^1, whatever. May the smarts be with you./%", "obj_ch2_scene23d_slash_Step_0_gml_203_0")
    c_talk_wait()
    c_wait(10)
    c_soundplay(snd_jump)
    c_jump_sprite(278, ((cameray() + view_hport[0]) + 200), 20, 30, spr_susie_dw_fall_d, spr_susie_dw_landed)
    c_wait(30)
    c_sel(no)
    c_walkdirect(263, 244, 15)
    c_sel(be)
    c_walkdirect(326, 256, 15)
    c_wait(15)
    c_sel(no)
    c_facing("d")
    c_sel(be)
    c_facing("berdlyunhappy")
    c_facing("d")
    c_wait(30)
    c_speaker("berdly")
    c_msgsetloc(0, "\\E0* Ah..^1. she left before I could.../", "obj_ch2_scene23d_slash_Step_0_gml_233_0")
    c_msgnextloc("\\E9* ..../%", "obj_ch2_scene23d_slash_Step_0_gml_234_0")
    c_talk_wait()
    c_sel(be)
    c_facing("l")
    c_speaker("berdly")
    c_msgsetloc(0, "\\E9* Noelle. It's hard to say this./", "obj_ch2_scene23d_slash_Step_0_gml_242_0")
    c_msgnextloc("\\E5* You've done so much for me^1, and I.../", "obj_ch2_scene23d_slash_Step_0_gml_243_0")
    c_msgnextloc("\\E8* Noelle..^1. I'm sorry./%", "obj_ch2_scene23d_slash_Step_0_gml_244_0")
    c_talk_wait()
    c_sel(no)
    c_facing("r")
    c_speaker("noelle")
    c_msgsetloc(0, "\\EF* Berdly...? You're..^1. actually apologizing?/%", "obj_ch2_scene23d_slash_Step_0_gml_252_0")
    c_talk_wait()
    c_facing("d")
    c_speaker("noelle")
    c_msgsetloc(0, "\\E9* ..^1. Thank you. I..^1. I understand^1, you know?/", "obj_ch2_scene23d_slash_Step_0_gml_259_0")
    c_msgnextloc("\\E2* You've always..^1. been nice to me when it's just the two of us./%", "obj_ch2_scene23d_slash_Step_0_gml_260_0")
    c_talk_wait()
    c_facing("r")
    c_speaker("noelle")
    c_msgsetloc(0, "\\E4* You just wanted to make a happy world for me./%", "obj_ch2_scene23d_slash_Step_0_gml_267_0")
    c_talk_wait()
    c_facing("l")
    c_speaker("noelle")
    c_msgsetloc(0, "\\EH* I'm..^1. glad you realized^1, um..^1. it sucked./%", "obj_ch2_scene23d_slash_Step_0_gml_274_0")
    c_talk_wait()
    c_sel(be)
    c_facing("d")
    c_speaker("berdly")
    c_msgsetloc(0, "\\E3* Oh./%", "obj_ch2_scene23d_slash_Step_0_gml_282_0")
    c_talk_wait()
    c_sel(no)
    c_facing("r")
    c_speaker("noelle")
    c_msgsetloc(0, "\\E2* Huh?/%", "obj_ch2_scene23d_slash_Step_0_gml_290_0")
    c_talk_wait()
    c_sel(be)
    c_facing("berdlydark")
    c_facing("l")
    c_speaker("berdly")
    c_msgsetloc(0, "\\EI* I mean^1, YES^1, I WAS^1, in a WAY^1,/", "obj_ch2_scene23d_slash_Step_0_gml_299_0")
    c_msgnextloc("\\E4* Apologizing for THAT^1, but./%", "obj_ch2_scene23d_slash_Step_0_gml_300_0")
    c_talk_wait()
    c_facing("d")
    c_speaker("berdly")
    c_msgsetloc(0, "\\E5* I also wanted to apologize./%", "obj_ch2_scene23d_slash_Step_0_gml_307_0")
    c_talk_wait()
    c_sprite(spr_berdly_depressed_dw_right)
    c_speaker("berdly")
    c_msgsetloc(0, "\\EG* For leading you on./", "obj_ch2_scene23d_slash_Step_0_gml_314_0")
    c_facenext("noelle", 16)
    c_msgnextloc("\\EG /", "obj_ch2_scene23d_slash_Step_0_gml_316_0")
    c_facenext("berdly", 8)
    c_msgnextloc("\\E8* I know you only always helped me out because^1, well.../%", "obj_ch2_scene23d_slash_Step_0_gml_318_0")
    c_talk_wait()
    c_autofacing(0)
    c_sprite(spr_berdly_walk_right_dw_unhappy)
    c_walk_wait("r", 5, 10)
    c_wait(15)
    c_sprite(spr_berdly_depressed_dw_right)
    c_speaker("berdly")
    c_msgsetloc(0, "\\EH* You had a crush on me^1, so.../%", "obj_ch2_scene23d_slash_Step_0_gml_327_0")
    c_talk_wait()
    c_sel(no)
    c_sprite(spr_noelle_shocked_dw)
    c_shakeobj()
    c_speaker("noelle")
    c_msgsetloc(0, "\\EI* WHAT?/%", "obj_ch2_scene23d_slash_Step_0_gml_338_0")
    c_talk_wait()
    c_sel(be)
    c_autofacing(1)
    c_walk_wait("l", 5, 10)
    c_speaker("berdly")
    c_msgsetloc(0, "\\E3* O-oh^1, sorry^1! Please^1, don't be embarrassed!/%", "obj_ch2_scene23d_slash_Step_0_gml_346_0")
    c_talk_wait()
    c_facing("d")
    c_sel(no)
    c_facing("r")
    c_speaker("berdly")
    c_msgsetloc(0, "\\E4* It's understandable. But^1, I..^1. I have to tell you I.../%", "obj_ch2_scene23d_slash_Step_0_gml_356_0")
    c_talk_wait()
    c_sel(be)
    c_sprite(spr_berdly_depressed_dw_left)
    c_speaker("berdly")
    c_msgsetloc(0, "\\E5* I really value your friendship^1, OK? So I.../", "obj_ch2_scene23d_slash_Step_0_gml_364_0")
    c_msgnextloc("\\EG* I..^1. felt I had to pretend to reciprocate those feelings.../%", "obj_ch2_scene23d_slash_Step_0_gml_365_0")
    c_talk_wait()
    c_sel(no)
    c_sprite(spr_noelle_shocked_dw)
    c_shakeobj()
    c_speaker("noelle")
    c_msgsetloc(0, "\\EI* WHAT? But I..^1. I don't -- I never --/%", "obj_ch2_scene23d_slash_Step_0_gml_374_0")
    c_talk_wait()
    c_sel(be)
    c_autofacing(1)
    c_walk("r", 5, 10)
    c_speaker("berdly")
    c_msgsetloc(0, "\\E5* Furthermore^1, I think I may have.../%", "obj_ch2_scene23d_slash_Step_0_gml_382_0")
    c_talk_wait()
    c_wait(30)
    c_facing("l")
    c_speaker("berdly")
    c_msgsetloc(0, "\\EM* Discovered someone else for me./%", "obj_ch2_scene23d_slash_Step_0_gml_392_0")
    c_talk_wait()
    c_sel(no)
    c_sprite(spr_noelle_shocked_dw)
    c_shakeobj()
    c_speaker("noelle")
    c_msgsetloc(0, "\\EH* HUH????????????/%", "obj_ch2_scene23d_slash_Step_0_gml_401_0")
    c_talk_wait()
    c_sel(be)
    c_walkdirect_wait(302, 252, 10)
    c_facing("d")
    c_speaker("berdly")
    c_msgsetloc(0, "\\E5* Please don't be jealous./", "obj_ch2_scene23d_slash_Step_0_gml_410_0")
    c_facenext("noelle", "I")
    c_msgnextloc("\\EI* OF????????????????&???????????????/%", "obj_ch2_scene23d_slash_Step_0_gml_412_0")
    c_talk_wait()
    c_mus("stop")
    c_mus("free_all")
    c_speaker("berdly")
    c_msgsetloc(0, "\\E4* Susie/%", "obj_ch2_scene23d_slash_Step_0_gml_419_0")
    c_talk_wait()
    c_sel(be)
    c_visible(0)
    c_sel(no)
    c_autowalk(false)
    c_sprite(spr_cutscene_23d_noelle_berdly_shake)
    c_addxy(6, -4)
    c_shakeobj()
    c_soundplay(snd_damage)
    c_imageindex(0)
    c_imagespeed(0.25)
    if (global.lang != "ja")
    {
        for (var _n = 0; _n < 12; _n++)
        {
            c_delaycmd((19 + (_n * 16)), "shakeobj", 0)
            c_delaycmd((19 + (_n * 16)), "soundplay", 167)
        }
    }
    else
    {
        var n_offset = 0
        for (_n = 0; _n < 11; _n++)
        {
            if (_n == 5)
                n_offset = 2
            if (_n == 6)
                n_offset = -3
            c_delaycmd(((19 + (_n * 12)) + n_offset), "shakeobj", 0)
            c_delaycmd(((19 + (_n * 12)) + n_offset), "soundplay", 167)
        }
    }
    c_speaker("noelle")
    c_msgsetloc(0, "\\s0\\EK* WHAT^2? WHAT^2? WHAT^2? WHAT^2? WHAT^2? WHAT^2? WHAT^2? WHAT^2? WHAT^2? WHAT^2? WHAT^2? WHAT^2?%%", "obj_ch2_scene23d_slash_Step_0_gml_433_0")
    c_talk_wait()
    c_var_instance(blackall, "image_alpha", 1)
    c_wait(120)
    c_actortokris()
    c_terminatekillactors()
}
if (con == 50 && (!i_ex(obj_cutscene_master)))
{
    con = 0
    global.flag[319] = 3
    room_goto(room_dw_mansion_acid_tunnel_exit)
}
if release_berdly
{
    release_berdly = 0
    berdly_glide = instance_create(-100, -100, obj_berdly_rose)
}
if hide_berdly
{
    hide_berdly = 0
    with (berdly_glide)
        instance_destroy()
}
