f = 2
image_xscale = 2
image_yscale = 2
x = 320
y = 300
depth = 9
randomize()
bg = instance_create(x, y, o_boxing_black_battle_bg)
bg.depth = (depth + 1)
health_count = 1500
health_count_max = 1500
health_count_prev = 1500
if (room == room_dw_mansion_top || room == room_battletest)
{
    instance_create(0, 0, obj_thrash_transformation_transition)
    health_count = 1500
    health_count_max = 1500
    health_count_prev = 1500
}
else
{
    health_count = 1000
    health_count_max = 1000
    health_count_prev = 1000
}
health_count_prev_timer_set = (48 / f)
health_count_prev_timer = 0
white_flash = 0
rand_fix = 0
vertical_laser_amount = 3
arc_movement = 0
horizontal_laser_amount = 2
flametimer = 0
specialcon = 0
specialcontimer = 0
baseball_amount = 1
baseball_timer = 0
baseball_timer_max = (48 / f)
baseball_hit_boss_number = 0
first_normal_baseball_throw = 0
phase_transition = 0
phase_transition_timer = 0
stomp_speed = 0.1
force_drawflip = 0
first_octagon_attack = 0
player_dead_timer = 0
pattern_phase = 0
pattern_state = 0
has_boss_done_pattern7 = false
final_sequence_red_alpha = 0
final_sequence_red_state = 0
crescent_explosion_timer = 0
text_state = 0
hurt_fx1_timer = 0
hurt_fx1_timer2 = 0
hurt_fx1_state = 1
hurt_fx2_state = 1
hurt_fx2_timer = 0
times_hit_in_a_row = 0
damagetakenincrease = 0
actpunchtimer = 0
playerhitbykick = false
shortcomboend = 0
shaketimer = 0
readycon = 0
finalbaseballused = false
firstquickpunch = 1
arcadebaseballused = false
finalphasearcadecon = 0
usedbaseball = 0
kicks_done = 0
attackorderlooping = 0
phaseprevious = 0
attackorderloopingturn = 0
pacifist = 1
dodgehintcount = 3
duckhintcount = 3
delayattack = 0
delayattacktelegraph = 0
firstwheelattack = 0
firstwheelattackdelay = 0
original_depth = depth
attackcon = 0
attacktype = 1
punch_amount = 1
punch_type = 0
kick_amount = 1
splash_amount = 1
pirouette_amount = 1
pirouette_type = 1
wheel_amount = 3
wheel_type = 0
siner = 0
con = 0
timer = 0
state = 0
makedizzy = 0
dizzytimer = 0
hurttimer = 0
blocktimer = 0
substate = 0
vshake = 0
vshaketimer = 0
idletimer = 0
fsiner = 0
init = false
path = -1
combo = 0
ohpitch = 0
savex = 0
savey = 0
movetimer = 0
drawflip = 0
index_previous = 0
explosion_snd_count = 0
basex = x
basey = y
flipthreshold = (120 / f)
fliptimer = 0
attackthreshold = (90 / f)
attack_succeded = 0
attackthresholddefault = attackthreshold
wheelsoundtimer = 0
bouncetimer = 0
image_speed = 0
invincible_l = 0
invincible_r = 0
blocking = -1
noattack = 0
nextdrawflip = -1
turnbased = 1
myturn = 0
debug_text = "nothing"
maxpattern = 14
useattacklist = 1
scr_qb_reset()
if (o_boxingcontroller.wireframe_boxing == 1)
    sprite_index = spr_bqueen_wireframe
if (room == room_dw_cyber_queen_boxing)
    arcade = true
else
    arcade = false
