loaded = false
save_ready = false
save_loaded = false
var ww = window_get_width()
var wh = window_get_height()
image_blend = c_black
fadespeed = 0
image_alpha = 0
alpha_set = 0
length = ww
height = wh
x = -20
y = -20
