image_xscale = 2
image_yscale = 2
image_speed = 0.25
global.charinstance[0] = obj_mainchara
global.charinstance[1] = global.cinstance[0]
global.charinstance[2] = global.cinstance[1]
timer = 0
siner = 0
shottimer = 0
con = 0
multiplier = 2
timermax = 0
shotcount = 0
gentimer = 0
hspeeddes = 0
viroBeltXPos = (2300 - sprite_width)
battleEndPos = 2360
nottooclose = 180
